### ISSUE TITLE
Warning: Cannot load LoopBack app server/server.js Use --force to continue.

### ISSUE THREAD

**Issue by manuchap** [beeman/loopback-angular-admin#1]
Firstly, thanks a million for this fantastic app!!!
I have it working but some dependencies were not met at first grunt.
Doing a PR with modified package file.

(for future readers who might bumb into an `Error: listen EADDRINUSE` after a successful grunt, try the following to kill running npm tasks you might have launched by trying stuff:

``` shell
ps aux | grep node
Find the process ID (second from the left)
kill -9 PRCOCESS_ID
```

**Comment by jgauna** [comment]
This happens everytime I run the project with ```grunt serve```. Btw, thanks for this incredibly project !

**Comment by beeman** [comment]
@jgauna I'm glad it is working for you. 

There should be no need for downgrading to node version 0.10 though. I've been working on this project with the latest io.js, version 3.0.0 and everything seems to be working well.

I'm using `n` to use different node versions, it has support for iojs too:  https://www.npmjs.com/package/n
