### ISSUE TITLE
Server side validations on registration

### ISSUE THREAD

**Issue by maisnamraju** [beeman/loopback-angular-admin#104]
This may be stupid, but is there a way to add server side validation on registration. Is this possible in the current app ?

**Comment by beeman** [comment]
@maisnamraju this should for sure be possible. I think you can do so by adding validation to the app's `User` model. 

For any further information I think it's best to ask in https://gitter.im/beeman/loopback-angular-admin or https://gitter.im/strongloop/loopback .
