### ISSUE TITLE
loopback-component-passport uses cookie: `access_token` not accessToken

### ISSUE THREAD

**Issue by njcaruso** [beeman/loopback-angular-admin#109]
In passpost-configurator.js, loopback is using the cookie `access_token`.

In your anuglarjs code `appauth.service.js` you're checking `$cookies.accessToken`.  I believe this should be changed to `$cookies.access_token`.

**Comment by yshing** [comment]
Check this: https://github.com/strongloop/loopback-component-passport/issues/57

**Comment by OwenBrotherwood** [comment]
@njcaruso Do you still believe this should be $cookies.access_token?

Another issue that should be thought about is the use of cookies as accessToken, contra other methods.

Thought in progress ...

---

https://github.com/beeman/loopback-angular-admin/blob/master/client/app/modules/users/services/appauth.service.js#L59

**Comment by beeman** [comment]
Social login should work again. Please reopen this issue if the issue is still relevant, with steps to reproduce. Thanks!
