### ISSUE TITLE
Logging in using google

### ISSUE THREAD

**Issue by reubenb87** [beeman/loopback-angular-admin#110]
Not sure if it's something I'm doing wrong. After cloning from git and only configuring the google and google-link providers I am able to successfully create a user using google provider. 
However when I click the 'Google' button on sign in page `/#/login` it redirects to google and when it takes me back I have the following in the server console:
>Logged in { username: 'google-login.1085811727xxxx',
>  password: '$2a$10xxxx',
>  email: 'xxxx@gmail.com',
>  status: 'created',
>  created: Thu Aug 13 2015 12:44:10 GMT+0000 (UTC),
>  id: 3 }

But in the console in the client I always get:
>GET https://xxxxx/api/users/1 401 (Unauthorized) from angular- scenario.js:19094 

Is there something I'm configuring wrong, I'm not sure why it's always trying to go to user id=1, when it should be 3?

**Comment by yshing** [comment]
Sadly found out that 'loopback-component-passport' is basically a useless module which cannot be rely on.
The social identity login function find related user by this query. 

'query = {"or":[{"username":"google-login.1085811727xxxx"},{"email":"xxx@gmail.com"}]}'

You'll only successfully link a account if you use the same email  - _ -..

Besides, it uses 'user.findOrCreate' inside the [login function](https://github.com/strongloop/loopback-component-passport/blob/master/lib/models/user-identity.js#L134) .......

**Comment by rualatngua** [comment]
+1 I got the same problem too :(

**Comment by ktersius** [comment]
I've created a pull request that gets passport working again. https://github.com/beeman/loopback-angular-admin/pull/135

**Comment by sakthideveloper** [comment]
Hi ktersius, 
   Really a great works. It's works perfectly right now.
