### ISSUE TITLE
QuotaExceededError causes login to fail on Safari 8.0.5

### ISSUE THREAD

**Issue by absurd** [beeman/loopback-angular-admin#111]
<img width="835" alt="screen shot 2015-08-19 at 11 36 52 am" src="https://cloud.githubusercontent.com/assets/2117288/9365546/0042ddfa-4667-11e5-9229-7b310b937dea.png">

**Comment by sahat** [comment]
@absurd Are you running it in Safari Private Window?

**Comment by absurd** [comment]
@sahat Oh of course, unavailable localStorage. Yes, I was.
