### ISSUE TITLE
Routed back to /login even with a token

### ISSUE THREAD

**Issue by asgeirbirkis** [beeman/loopback-angular-admin#114]
I'm finding myself in the situation that if I restart the server, then go back to 0.0.0.0:9000 , I always get routed back to the login page, even if I have a token. Looking into the issue, it appears that the lines to blame are in `client/app/modules/core/controllers/router.ctrl.js`, more precisely,

```
    ApiService.checkConnection()
      .then(function() {
        console.log('ApiService.checkConnection success');
        if (!AppAuth.currentUser) {
          $location.path('/login');
        } else {
          $location.path('/app');
        }
      })
```

For some reason, at this point, `AppAuth.currentUser` has not been set, so we go into the first part of the if statement. Is there any particular reason why not to use LoopBackAuth here instead of AppAuth? If I change the condition to
```
if (!LoopBackAuth.currentUserId)
```
I get the desired effect; routed to /app if I have a token, otherwise, taken to /login .

**Comment by beeman** [comment]
This issue should be fixed. If not, please reopen with the steps to reproduce.
