### ISSUE TITLE
MultiCheckbox and formly-bootstrap-template require a higher lib version

### ISSUE THREAD

**Issue by brunoshow** [beeman/loopback-angular-admin#118]
Hi, I'm trying do a multicheckbox or some kind of array selection to my model exemple 
Model Result (something like) -> "Features": [ 'a', 'b', 'c' ]

For this I've tried to add angular-formly-templates-bootstrap but it require a higher formly version, then when I update it I catch `formlyConfigProvider.setTemplateUrl is not a function` in core.config

Does someone know another way to do the same on this project or resolve this?

**Comment by beeman** [comment]
Hi @brunoshow, I've just updated formly to these versions:

```
"angular-formly": "6.24.23",
"angular-formly-templates-bootstrap": "6.0.0",
``` 

Can you try it again and maybe add an example in the app's Sandbox for it? Thanks!

**Comment by brunoshow** [comment]
I did a pull now you don't have this 'app.config(function(formlyConfigProvider) {' so its not happening anymore,
thanks
