### ISSUE TITLE
Auto generate forms by backend model?

### ISSUE THREAD

**Issue by portokallidis** [beeman/loopback-angular-admin#119]
Would be really nice for prototyping...
How can i retrieve a loopback backend model schema through angular?
I want to build automatic forms based on the backend models... i think it is possible

**Comment by beeman** [comment]
It would indeed be really nice to have that.

Last week I've add a couple of methods to a model called `Meta` that can be used for this purpose.

The methods are:
```
/Meta/getModelAcls
/Meta/getModelProperties
/Meta/getModelRelations
/Meta/getModelRemotes
/Meta/getModelSettings
```

I'm not sure if it gives all the information that is needed, but I guess it will be a start.

Another thing to not is that I'm most likely moving towards using schema-form, so it might be good to base it on that. Or at least abstract it in a way that it can support both angular-formly and schema-form. 

I know @drmikecrowe and @dot-louis have been working on something similar.

It's probably good to discuss the ideas in this issue or in the [gitter room](gitter.im/beeman/loopback-angular-admin). I'm happy to look at the code if you submit a PR!

**Comment by dot-louis** [comment]
Hi @portokallidis ,
I'm indeed working on a solution to complete the Loopback explorer: https://github.com/dot-louis/loopback-browser (not ready yet)

If you want to get the model schema, you can enable loopback explorer and query the following api from your app:
```js
// To get the api paths of your models
YOUR_HOST/explorer/resources
// To get the model schema
YOUR_HOST/explorer/resources/some_model_name_(plural)
```

For example you could have a function to request the available api endpoints,
and then get the related operations, and model details
```js

var resources = YOUR_HOST+'/explorer/resources';

function getResources(){
  return $http.get(resources)
  .then(function(res){
    // res looks something like this
    /*{
         "swaggerVersion": "1.2",
         "apiVersion": "1.0.0",
         "apis": [
           {
             "path": "/SomeModels"
           }
         ]
      }*/

     // Note that querying a single model will fetch the details for all models (it seems the only difference is the order of the apis in the JSON response)
     // So you only need to get the first one
     return $http.get(resources + res.apis[0].path);
  })
  .then(function(details){
  // details looks something like this:
  /*
  {
  "apiVersion": "1.0.0",
  "swaggerVersion": "1.2",
  "basePath": "YOUR_HOST",
  "resourcePath": "/SomeModels",
  "apis": [
    {
      "path": "/SomeModels/{id}/orignal",
      "operations": [
        {
          "method": "GET",
          "nickname": "prototype.__get__orignal",
          "parameters": [
            {
              "paramType": "query",
              "name": "refresh",
              "required": false,
              "allowMultiple": false,
              "type": "boolean"
            },
            {
              "paramType": "path",
              "name": "id",
              "description": "PersistedModel id",
              "required": true,
              "allowMultiple": false,
              "type": "any"
            }
          ],
          "responseMessages": [
            {
              "code": 200,
              "message": "Request was successful"
            }
          ],
          "summary": "Fetches belongsTo relation orignal.",
          "type": "SomeModel"
        }
      ]
    }
   ...
  */
  });
}
```

You should have all the data you need to build your forms based on your loopback models.
However be careful as loopback explorer is probably not meant to be used in production (because security).
The other method would be as @beeman suggested which is creating a Meta model that will return other models' data for you.

**Comment by portokallidis** [comment]
Hi,
@dot-louis this was my first approach,then i explored the Meta model @beeman  has created and that was very helpful although i couldn't retrieve somehow the type(string,number,etc) of properties... 
Thank you for the help!

**Comment by beeman** [comment]
@dot-louis thanks for your input :) 

@portokallidis where would you expect these details to appear? In one of the existing methods or in a new one? It would be quite straightforward to add them

**Comment by portokallidis** [comment]
Perhaps nested like they are in common models

         prop_name: {
              type:"string",
              required:true
         }

**Comment by beeman** [comment]
I've just added a basic data browser. I've not yet implemented #121 in the updated Meta model as it seemed to crashed the server.

So it seems that the property definition is stored as a function instead of a string?

**Comment by portokallidis** [comment]
yes it does, the first commit crashes the server and the second does not. I think the server crashes because i tried to manipulate a function object and make it string.
What i did next is that i left "type" as it is and created a new type "stringType" and now it doesnt crash although is not clean

**Comment by beeman** [comment]
It looks like this does it: https://github.com/beeman/loopback-angular-admin/blob/9845ed2e8166d92da7a9e8a11b1aab545b863c32/common/models/meta.js#L9

**Comment by beeman** [comment]
Data browser is in place, closing this issue.
