### ISSUE TITLE
Anyone having problem with the uglify grunt task

### ISSUE THREAD

**Issue by portokallidis** [beeman/loopback-angular-admin#123]
I think it is consuming a lot of memory, i am using cloud9 ide and sometimes crashes due to low memory (1gb) 
Is there anyway to limit memory consumption?
I tried to upgrade to 0.8.1 and it gets stuck over 5min
Any ideas?

**Comment by portokallidis** [comment]
6min 25sec just for the uglify

**Comment by beeman** [comment]
Closing in favor of work on project based on Angular 2+ / TypeScript. Follow here https://github.com/beeman/loopback-angular-admin/issues/202
