### ISSUE TITLE
Configure to work on remote machine requires changing Gruntfile.js

### ISSUE THREAD

**Issue by drorm** [beeman/loopback-angular-admin#124]
I did a fresh install on a remote server.

If I don't change anything or change server/config.json:
```
-  "host": "0.0.0.0",
+  "host": "my.server.com",
   "port": 3000,
-  "url": "http://localhost:3000/",
+  "url": "http://my.server.com:3000/",
```

I get a bunch of errors trying to read the REST API and get redirected to http://my.server.com:3000/#/error

If I also change
```
Gruntfile.js
     api: {
-      development: 'http://0.0.0.0:3000/api/',
+      development: 'http://my.server.com:3000/api/',
       production: '/api/'
     },
     site: {
-      development: 'http://0.0.0.0:3000',
+      development: 'http://my.server.com:3000',
       production: ''
     },
-    host: '0.0.0.0'
+    host: 'my.server.com'
```

Everything works correctly.

**Comment by beeman** [comment]
Can you try to see if setting the `API_URL` to `http://my.server.com:3000/api/` fixes this? It's mentioned in the README

**Comment by sakthideveloper** [comment]
Hi Bram,

 When I've using oauth implementation in the loopback angular admin it will
returning to login but I've got data in UserIdentity Model. Please help me
As soon as possible.

**Comment by beeman** [comment]
@sakthideveloper Please check one of the existing tickets about authentication or open a new one for this as it has not to do with this issue.

**Comment by sakthideveloper** [comment]
Okay Thankyou Bram and sorry I've asked this questions from this ticket.

**Comment by drorm** [comment]
setting the API_URL does not fix it.
The problem is in here:
```
 loopback_sdk_angular: {
      services: {
        options: {
          input: 'server/server.js',
          output: '<%= yeoman.app %>/js/lb-services.js',
          apiUrl: '<%= yeoman.api.development %>'
        }
      },

**Comment by beeman** [comment]
Not sure if this is still relevant or how to reproduce it, it seems to work fine when I run it on a remote instance. Please reopen with steps to reproduce if the issue is still relevant.
