### ISSUE TITLE
Update built-in templates and update to formly v7.x

### ISSUE THREAD

**Issue by kentcdodds** [beeman/loopback-angular-admin#125]
I've just [discovered this](http://stackoverflow.com/questions/32461344/angularjs-formly-nested-form/32461451?noredirect=1#comment52784923_32461451). How cool! Glad that you're using angular-formly. I looked at some of the custom templates and it looks like they were copied from angular-formly-templates-bootstrap a long time ago. There's been a lot of improvements since those were released and could probably use an update.

I also noticed from some of the github issues that some people seem to just be using the latest angular-formly-templates-bootstrap which makes more sense to me, so you may consider just removing the templates from the repo altogether.

Anyway, I don't really have a use case for this right now, I just thought I'd ping you here and let you know about the updates :-) Happy coding! :computer:

**Comment by beeman** [comment]
Hi @kentcdodds , thanks for you message and of course for creating angular-formly!

I've just upgraded to version 6 with the intention to just make it work, I will still need to do some refactoring to get all custom elements the way I want them. I'll than upgrade to version 7 too.

So yeah, these can probably all go: https://github.com/beeman/loopback-angular-admin/tree/master/client/app/modules/core/views/elements

**Comment by beeman** [comment]
Closing in favor of work on project based on Angular 2+ / TypeScript. Follow here https://github.com/beeman/loopback-angular-admin/issues/202
