### ISSUE TITLE
Permissioning

### ISSUE THREAD

**Issue by kentyap** [beeman/loopback-angular-admin#126]
Hi

I found that anyone can access any object without authentication. 
Hence I try to block unauthenticated users from accessing one of the common object like Event.json
By adding the following acl, 
 {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$unauthenticated",
      "permission": "DENY"
    }

I encounter the following error when loading in the console of the browser when refreshing the login page without any login.
Failed to load resource: the server responded with a status of 401 (Unauthorized)http://localhost:3000/api/event.

I found that i was able to login using account register directly but failed to login in for social login.
For social login it keep redirect back to login in page.

I also find that the above acl successfully block any unauthenticated user to http://localhost:3000/api/event . 

Otherwise please advise how to block unauthenticated accessing any of the objects in the system if the above method is not correct.

**Comment by drorm** [comment]
From the README:
"Please note, at this moment there is no difference in permissions for admin users or regular users. This needs to change in the future!"

I'm looking at how to resolve this too. It's a combination of figuring out the right ACLs, but will probably involve code changes too.

**Comment by kentyap** [comment]
The problem is even unauthenticated users can access all the endpoints but what I face is even if I manage to block unauthenticated users but it throw error of 401 and it seems that there is a bug for social login that will be redirect back to login page . It seems to be fine for registered login.

**Comment by beeman** [comment]
@kentyap the bug with the social login should be fixed. Please reopen this ticket with a bit more specific info or open a new one if you still have issues with the ACL's. It would be helpful if you have a fork that shows the issue.
