### ISSUE TITLE
Dashboard only updates when don refresh.

### ISSUE THREAD

**Issue by spalaussie** [beeman/loopback-angular-admin#128]
I'm facing issue with dashboard boxes not displaying current count. is this an issue or I'm missing something. 
Dashboard box values doesn't update values  upon login or clicking on Dashboard link. It only updates with current values in boxes upon reresh (f5).

can anyone help we this issue.

Thanks

**Comment by beeman** [comment]
Closing in favor of work on project based on Angular 2+ / TypeScript. Follow here https://github.com/beeman/loopback-angular-admin/issues/202
