### ISSUE TITLE
Restructure project and migrate to gulp

### ISSUE THREAD

**Issue by beeman** [beeman/loopback-angular-admin#129]
### Motivation

The project can use a better folder structure. The idea is to keep the top level folder clean with all the files needed to run and build the project. All source code will reside in the `src` folder.

I will take this opportunity to migrate from `grunt` to `gulp` as I think it is cleaner to work with. 

The `gulp` build system should do everything that the current `grunt` build system does.

### Suggested structure

Name | Description
--------|--------
dist/ | The result of a project build 
docs/ | The documentation 
gulp/ | The gulp configuration details
src/ | All the sources
src/client/ | AngularJS admin app
src/common/models | LoopBack model definition
src/server/ | LoopBack server
package.json | Main package.json
gulpfile.js | Main gulp configuration

**Comment by movibe** [comment]
My suggestion for app folder and gulp files

| Name|Description|
|-----|:------|
| app |AngularJS admin App |
| app/lib |for bower_components folder |
| app/module/**/*.spec.js|Auto detect file for Angular Tests with ignore using gulp-inject |
| gulpfile.config.js |Configurations for gulp |
| gulpfile.js |Gulp Tasks |

**Comment by beeman** [comment]
@movibe the point in the structure I suggested is that the code is in a subfolder `src` to keep the root clean. Also I think it is nice to have the code separated from the other files in the project.

I do think it's fine to move from `src/client/app` to `src/client`, I've update the layout in the first post.
