### ISSUE TITLE
Cannot run the server!!!

### ISSUE THREAD

**Issue by sithuhein** [beeman/loopback-angular-admin#132]
When i run the 'grunt serve' command, it showing this error..

Error Log!!!
===============================================================================
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\sithu\\nvmw\\nodejs\\v0.10.40\\\\node.exe',
1 verbose cli   'C:\\Users\\sithu\\nvmw\\nodejs\\v0.10.40\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@1.4.12
3 info using node@v0.10.40
4 verbose node symlink C:\Users\sithu\nvmw\nodejs\v0.10.40\\node.exe
5 verbose readDependencies using package.json deps
6 verbose install where, deps [ 'E:\\Temp\\StrongLoop\\loopback-angular-admin-master',
6 verbose install   [ 'async',
6 verbose install     'body-parser',
6 verbose install     'bower',
6 verbose install     'compression',
6 verbose install     'connect-ensure-login',
6 verbose install     'cookie-parser',
6 verbose install     'debug',
6 verbose install     'errorhandler',
6 verbose install     'eventemitter3',
6 verbose install     'express-session',
6 verbose install     'faker',
6 verbose install     'get-env',
6 verbose install     'grunt',
6 verbose install     'grunt-angular-gettext',
6 verbose install     'grunt-autoprefixer',
6 verbose install     'grunt-cli',
6 verbose install     'grunt-concurrent',
6 verbose install     'grunt-connect-proxy',
6 verbose install     'grunt-contrib-clean',
6 verbose install     'grunt-contrib-concat',
6 verbose install     'grunt-contrib-connect',
6 verbose install     'grunt-contrib-copy',
6 verbose install     'grunt-contrib-cssmin',
6 verbose install     'grunt-contrib-htmlmin',
6 verbose install     'grunt-contrib-jshint',
6 verbose install     'grunt-contrib-uglify',
6 verbose install     'grunt-contrib-watch',
6 verbose install     'grunt-docular',
6 verbose install     'grunt-filerev',
6 verbose install     'grunt-google-cdn',
6 verbose install     'grunt-include-source',
6 verbose install     'grunt-jsbeautifier',
6 verbose install     'grunt-karma',
6 verbose install     'grunt-loopback-sdk-angular',
6 verbose install     'grunt-newer',
6 verbose install     'grunt-ng-annotate',
6 verbose install     'grunt-ng-constant',
6 verbose install     'grunt-svgmin',
6 verbose install     'grunt-usemin',
6 verbose install     'grunt-wiredep',
6 verbose install     'gulp-nodemon',
6 verbose install     'jshint',
6 verbose install     'jshint-stylish',
6 verbose install     'load-grunt-tasks',
6 verbose install     'lodash',
6 verbose install     'loopback',
6 verbose install     'loopback-boot',
6 verbose install     'loopback-component-passport',
6 verbose install     'loopback-component-storage',
6 verbose install     'loopback-connector-mongodb',
6 verbose install     'loopback-datasource-juggler',
6 verbose install     'nodemon',
6 verbose install     'passport',
6 verbose install     'passport-facebook',
6 verbose install     'passport-google-oauth',
6 verbose install     'passport-local',
6 verbose install     'passport-oauth2',
6 verbose install     'passport-twitter',
6 verbose install     'serve-favicon',
6 verbose install     'showdown',
6 verbose install     'time-grunt',
6 verbose install     'loopback-explorer',
6 verbose install     'browserify',
6 verbose install     'connect-livereload',
6 verbose install     'jasmine-core',
6 verbose install     'karma',
6 verbose install     'karma-cli',
6 verbose install     'karma-coverage',
6 verbose install     'karma-jasmine',
6 verbose install     'karma-phantomjs-launcher',
6 verbose install     'run-sequence',
6 verbose install     'tiny-lr' ] ]
7 info preinstall loopback-angular-admin@0.1.1
8 warn package.json karma-coverage@0.2.7 No README data
9 verbose readDependencies using package.json deps
10 verbose already installed skipping async@0.9.0 E:\Temp\StrongLoop\loopback-angular-admin-master
11 verbose already installed skipping body-parser@1.11.0 E:\Temp\StrongLoop\loopback-angular-admin-master
12 verbose already installed skipping bower@1.3.12 E:\Temp\StrongLoop\loopback-angular-admin-master
13 verbose already installed skipping compression@1.4.0 E:\Temp\StrongLoop\loopback-angular-admin-master
14 verbose already installed skipping connect-ensure-login@0.1.1 E:\Temp\StrongLoop\loopback-angular-admin-master
15 verbose already installed skipping cookie-parser@1.3.3 E:\Temp\StrongLoop\loopback-angular-admin-master
16 verbose already installed skipping debug@2.1.3 E:\Temp\StrongLoop\loopback-angular-admin-master
17 verbose already installed skipping errorhandler@1.3.3 E:\Temp\StrongLoop\loopback-angular-admin-master
18 verbose already installed skipping eventemitter3@0.1.6 E:\Temp\StrongLoop\loopback-angular-admin-master
19 verbose already installed skipping express-session@1.10.2 E:\Temp\StrongLoop\loopback-angular-admin-master
20 verbose already installed skipping faker@3.0.1 E:\Temp\StrongLoop\loopback-angular-admin-master
21 verbose already installed skipping get-env@0.4.0 E:\Temp\StrongLoop\loopback-angular-admin-master
22 verbose already installed skipping grunt@0.4.5 E:\Temp\StrongLoop\loopback-angular-admin-master
23 verbose already installed skipping grunt-angular-gettext@2.0.1 E:\Temp\StrongLoop\loopback-angular-admin-master
24 verbose already installed skipping grunt-autoprefixer@2.2.0 E:\Temp\StrongLoop\loopback-angular-admin-master
25 verbose already installed skipping grunt-cli@0.1.13 E:\Temp\StrongLoop\loopback-angular-admin-master
26 verbose already installed skipping grunt-concurrent@1.0.0 E:\Temp\StrongLoop\loopback-angular-admin-master
27 verbose already installed skipping grunt-connect-proxy@0.2.0 E:\Temp\StrongLoop\loopback-angular-admin-master
28 verbose already installed skipping grunt-contrib-clean@0.6.0 E:\Temp\StrongLoop\loopback-angular-admin-master
29 verbose already installed skipping grunt-contrib-concat@0.5.0 E:\Temp\StrongLoop\loopback-angular-admin-master
30 verbose already installed skipping grunt-contrib-connect@0.9.0 E:\Temp\StrongLoop\loopback-angular-admin-master
31 verbose already installed skipping grunt-contrib-copy@0.7.0 E:\Temp\StrongLoop\loopback-angular-admin-master
32 verbose already installed skipping grunt-contrib-cssmin@0.11.0 E:\Temp\StrongLoop\loopback-angular-admin-master
33 verbose already installed skipping grunt-contrib-htmlmin@0.4.0 E:\Temp\StrongLoop\loopback-angular-admin-master
34 verbose already installed skipping grunt-contrib-jshint@0.11.0 E:\Temp\StrongLoop\loopback-angular-admin-master
35 verbose already installed skipping grunt-contrib-uglify@0.7.0 E:\Temp\StrongLoop\loopback-angular-admin-master
36 verbose already installed skipping grunt-contrib-watch@0.6.1 E:\Temp\StrongLoop\loopback-angular-admin-master
37 verbose already installed skipping grunt-docular@0.2.4 E:\Temp\StrongLoop\loopback-angular-admin-master
38 verbose already installed skipping grunt-filerev@2.1.2 E:\Temp\StrongLoop\loopback-angular-admin-master
39 verbose already installed skipping grunt-google-cdn@0.4.3 E:\Temp\StrongLoop\loopback-angular-admin-master
40 verbose already installed skipping grunt-include-source@0.4.5 E:\Temp\StrongLoop\loopback-angular-admin-master
41 verbose already installed skipping grunt-jsbeautifier@0.2.8 E:\Temp\StrongLoop\loopback-angular-admin-master
42 verbose already installed skipping grunt-karma@0.10.1 E:\Temp\StrongLoop\loopback-angular-admin-master
43 verbose already installed skipping grunt-loopback-sdk-angular@1.1.2 E:\Temp\StrongLoop\loopback-angular-admin-master
44 verbose already installed skipping grunt-newer@1.1.0 E:\Temp\StrongLoop\loopback-angular-admin-master
45 verbose already installed skipping grunt-ng-annotate@0.9.2 E:\Temp\StrongLoop\loopback-angular-admin-master
46 verbose already installed skipping grunt-ng-constant@1.0.0 E:\Temp\StrongLoop\loopback-angular-admin-master
47 verbose already installed skipping grunt-svgmin@2.0.0 E:\Temp\StrongLoop\loopback-angular-admin-master
48 verbose already installed skipping grunt-usemin@3.0.0 E:\Temp\StrongLoop\loopback-angular-admin-master
49 verbose already installed skipping grunt-wiredep@2.0.0 E:\Temp\StrongLoop\loopback-angular-admin-master
50 verbose already installed skipping gulp-nodemon@2.0.3 E:\Temp\StrongLoop\loopback-angular-admin-master
51 verbose already installed skipping jshint@2.6.0 E:\Temp\StrongLoop\loopback-angular-admin-master
52 verbose already installed skipping jshint-stylish@1.0.0 E:\Temp\StrongLoop\loopback-angular-admin-master
53 verbose already installed skipping load-grunt-tasks@3.1.0 E:\Temp\StrongLoop\loopback-angular-admin-master
54 verbose already installed skipping lodash@3.10.1 E:\Temp\StrongLoop\loopback-angular-admin-master
55 verbose already installed skipping loopback@2.19.0 E:\Temp\StrongLoop\loopback-angular-admin-master
56 verbose already installed skipping loopback-boot@2.6.4 E:\Temp\StrongLoop\loopback-angular-admin-master
57 verbose already installed skipping loopback-component-passport@1.1.2 E:\Temp\StrongLoop\loopback-angular-admin-master
58 verbose already installed skipping loopback-component-storage@1.2.0 E:\Temp\StrongLoop\loopback-angular-admin-master
59 verbose already installed skipping loopback-connector-mongodb@1.11.3 E:\Temp\StrongLoop\loopback-angular-admin-master
60 verbose already installed skipping loopback-datasource-juggler@2.33.1 E:\Temp\StrongLoop\loopback-angular-admin-master
61 verbose already installed skipping nodemon@1.3.7 E:\Temp\StrongLoop\loopback-angular-admin-master
62 verbose already installed skipping passport@0.2.1 E:\Temp\StrongLoop\loopback-angular-admin-master
63 verbose already installed skipping passport-facebook@1.0.3 E:\Temp\StrongLoop\loopback-angular-admin-master
64 verbose already installed skipping passport-google-oauth@0.1.5 E:\Temp\StrongLoop\loopback-angular-admin-master
65 verbose already installed skipping passport-local@1.0.0 E:\Temp\StrongLoop\loopback-angular-admin-master
66 verbose already installed skipping passport-oauth2@1.1.2 E:\Temp\StrongLoop\loopback-angular-admin-master
67 verbose already installed skipping passport-twitter@1.0.2 E:\Temp\StrongLoop\loopback-angular-admin-master
68 verbose already installed skipping serve-favicon@2.2.0 E:\Temp\StrongLoop\loopback-angular-admin-master
69 verbose already installed skipping showdown@0.3.1 E:\Temp\StrongLoop\loopback-angular-admin-master
70 verbose already installed skipping time-grunt@1.0.0 E:\Temp\StrongLoop\loopback-angular-admin-master
71 verbose already installed skipping loopback-explorer@1.6.4 E:\Temp\StrongLoop\loopback-angular-admin-master
72 verbose already installed skipping browserify@8.1.3 E:\Temp\StrongLoop\loopback-angular-admin-master
73 verbose already installed skipping connect-livereload@0.5.2 E:\Temp\StrongLoop\loopback-angular-admin-master
74 verbose already installed skipping jasmine-core@2.2.0 E:\Temp\StrongLoop\loopback-angular-admin-master
75 verbose already installed skipping karma@0.12.31 E:\Temp\StrongLoop\loopback-angular-admin-master
76 verbose already installed skipping karma-cli@0.0.4 E:\Temp\StrongLoop\loopback-angular-admin-master
77 verbose already installed skipping karma-coverage@0.2.7 E:\Temp\StrongLoop\loopback-angular-admin-master
78 verbose already installed skipping karma-jasmine@0.3.5 E:\Temp\StrongLoop\loopback-angular-admin-master
79 verbose already installed skipping karma-phantomjs-launcher@0.1.4 E:\Temp\StrongLoop\loopback-angular-admin-master
80 verbose already installed skipping run-sequence@1.0.2 E:\Temp\StrongLoop\loopback-angular-admin-master
81 verbose already installed skipping tiny-lr@0.1.5 E:\Temp\StrongLoop\loopback-angular-admin-master
82 silly resolved []
83 info build E:\Temp\StrongLoop\loopback-angular-admin-master
84 verbose linkStuff [ false, false, false, 'E:\\Temp\\StrongLoop' ]
85 info linkStuff loopback-angular-admin@0.1.1
86 verbose linkBins loopback-angular-admin@0.1.1
87 verbose linkMans loopback-angular-admin@0.1.1
88 verbose rebuildBundles loopback-angular-admin@0.1.1
89 verbose rebuildBundles [ '.bin',
89 verbose rebuildBundles   'async',
89 verbose rebuildBundles   'body-parser',
89 verbose rebuildBundles   'bower',
89 verbose rebuildBundles   'browserify',
89 verbose rebuildBundles   'compression',
89 verbose rebuildBundles   'connect-ensure-login',
89 verbose rebuildBundles   'connect-livereload',
89 verbose rebuildBundles   'cookie-parser',
89 verbose rebuildBundles   'debug',
89 verbose rebuildBundles   'errorhandler',
89 verbose rebuildBundles   'eventemitter3',
89 verbose rebuildBundles   'express-session',
89 verbose rebuildBundles   'faker',
89 verbose rebuildBundles   'get-env',
89 verbose rebuildBundles   'grunt',
89 verbose rebuildBundles   'grunt-angular-gettext',
89 verbose rebuildBundles   'grunt-autoprefixer',
89 verbose rebuildBundles   'grunt-cli',
89 verbose rebuildBundles   'grunt-concurrent',
89 verbose rebuildBundles   'grunt-connect-proxy',
89 verbose rebuildBundles   'grunt-contrib-clean',
89 verbose rebuildBundles   'grunt-contrib-concat',
89 verbose rebuildBundles   'grunt-contrib-connect',
89 verbose rebuildBundles   'grunt-contrib-copy',
89 verbose rebuildBundles   'grunt-contrib-cssmin',
89 verbose rebuildBundles   'grunt-contrib-htmlmin',
89 verbose rebuildBundles   'grunt-contrib-jshint',
89 verbose rebuildBundles   'grunt-contrib-uglify',
89 verbose rebuildBundles   'grunt-contrib-watch',
89 verbose rebuildBundles   'grunt-docular',
89 verbose rebuildBundles   'grunt-filerev',
89 verbose rebuildBundles   'grunt-google-cdn',
89 verbose rebuildBundles   'grunt-include-source',
89 verbose rebuildBundles   'grunt-jsbeautifier',
89 verbose rebuildBundles   'grunt-karma',
89 verbose rebuildBundles   'grunt-loopback-sdk-angular',
89 verbose rebuildBundles   'grunt-newer',
89 verbose rebuildBundles   'grunt-ng-annotate',
89 verbose rebuildBundles   'grunt-ng-constant',
89 verbose rebuildBundles   'grunt-svgmin',
89 verbose rebuildBundles   'grunt-usemin',
89 verbose rebuildBundles   'grunt-wiredep',
89 verbose rebuildBundles   'gulp-nodemon',
89 verbose rebuildBundles   'jasmine-core',
89 verbose rebuildBundles   'jshint',
89 verbose rebuildBundles   'jshint-stylish',
89 verbose rebuildBundles   'karma',
89 verbose rebuildBundles   'karma-cli',
89 verbose rebuildBundles   'karma-coverage',
89 verbose rebuildBundles   'karma-jasmine',
89 verbose rebuildBundles   'karma-phantomjs-launcher',
89 verbose rebuildBundles   'load-grunt-tasks',
89 verbose rebuildBundles   'lodash',
89 verbose rebuildBundles   'loopback',
89 verbose rebuildBundles   'loopback-boot',
89 verbose rebuildBundles   'loopback-component-passport',
89 verbose rebuildBundles   'loopback-component-storage',
89 verbose rebuildBundles   'loopback-connector-mongodb',
89 verbose rebuildBundles   'loopback-datasource-juggler',
89 verbose rebuildBundles   'loopback-explorer',
89 verbose rebuildBundles   'nodemon',
89 verbose rebuildBundles   'passport',
89 verbose rebuildBundles   'passport-facebook',
89 verbose rebuildBundles   'passport-google-oauth',
89 verbose rebuildBundles   'passport-local',
89 verbose rebuildBundles   'passport-oauth2',
89 verbose rebuildBundles   'passport-twitter',
89 verbose rebuildBundles   'run-sequence',
89 verbose rebuildBundles   'serve-favicon',
89 verbose rebuildBundles   'showdown',
89 verbose rebuildBundles   'time-grunt',
89 verbose rebuildBundles   'tiny-lr' ]
90 info install loopback-angular-admin@0.1.1
91 info postinstall loopback-angular-admin@0.1.1
92 verbose unsafe-perm in lifecycle true
93 info loopback-angular-admin@0.1.1 Failed to exec postinstall script
94 error loopback-angular-admin@0.1.1 postinstall: `bower install && grunt build`
94 error Exit status 6
95 error Failed at the loopback-angular-admin@0.1.1 postinstall script.
95 error This is most likely a problem with the loopback-angular-admin package,
95 error not with npm itself.
95 error Tell the author that this fails on your system:
95 error     bower install && grunt build
95 error You can get their info via:
95 error     npm owner ls loopback-angular-admin
95 error There is likely additional logging output above.
96 error System Windows_NT 6.2.9200
97 error command "C:\\Users\\sithu\\nvmw\\nodejs\\v0.10.40\\\\node.exe" "C:\\Users\\sithu\\nvmw\\nodejs\\v0.10.40\\node_modules\\npm\\bin\\npm-cli.js" "install"
98 error cwd E:\Temp\StrongLoop\loopback-angular-admin-master
99 error node -v v0.10.40
100 error npm -v 1.4.12
101 error code ELIFECYCLE
102 verbose exit [ 1, true ]

**Comment by brijs** [comment]
I get a similar error (with both node v0.12.5, v0.10.40)

14121 info install loopback-angular-admin@0.1.1
14122 info postinstall loopback-angular-admin@0.1.1
14123 verbose unsafe-perm in lifecycle true
14124 info loopback-angular-admin@0.1.1 Failed to exec postinstall script
14125 error loopback-angular-admin@0.1.1 postinstall: `bower install && grunt build`
14125 error Exit status 99
14126 error Failed at the loopback-angular-admin@0.1.1 postinstall script.
14126 error This is most likely a problem with the loopback-angular-admin package,
14126 error not with npm itself.
14126 error Tell the author that this fails on your system:
14126 error     bower install && grunt build
14126 error You can get their info via:
14126 error     npm owner ls loopback-angular-admin
14126 error There is likely additional logging output above.
14127 error System Darwin 14.4.0
14128 error command "/Users/bshetty/.nvm/v0.10.40/bin/node" "/Users/bshetty/.nvm/v0.10.40/bin/npm" "install"
14129 error cwd /Users/bshetty/tests/loopback-angular-admin
14130 error node -v v0.10.40
14131 error npm -v 1.4.28
14132 error code ELIFECYCLE

**Comment by beeman** [comment]
Should be fixed by #134
