### ISSUE TITLE
How to create modules so that it is reflected in AdminLTE frontend

### ISSUE THREAD

**Issue by aniruddhasm** [beeman/loopback-angular-admin#136]
Hello,

I've added models from my table. The models are added successfully in the backend i.e. 'sports.js, sports.json' but they are not reflected in the admin LTE. Also how to create modules in the client->app->modules section 
for example mine is sports
so that after adding client->app->js->app.js it will reflect in the admin UI.

Any help is appreciated.
Thanks,

**Comment by a3bhea** [comment]
@aniruddhasm did you manage to find a way to generate the module?

**Comment by denzelwamburu** [comment]
@aniruddhasm  You have to create the frontend files and place them in `/client/app/modules/` i.e
   -  `config/yourmodule.config.js`
   -  `config/yourmodule.routes.js`
   - `services/yourmodules.service.js`
   - `views/form.html`
   - `views/list.html`
   - `views/main.html`
   -`app.yourmodules.js`

Then add the location of your js files in `index.html` and remember to declare your module in `js/app.js`

**Comment by beeman** [comment]
There is currently not an easier way of doing this than what @denzelwamburu suggests. 

In the future there might be a generator for this, possibly based on this project: https://github.com/johannesjo/generator-angular-auto-admin-loopback

Also see https://github.com/beeman/loopback-angular-admin/issues/139 and https://github.com/beeman/loopback-angular-admin/issues/171 .
