### ISSUE TITLE
Generating modules for existing LB application

### ISSUE THREAD

**Issue by ianseyer** [beeman/loopback-angular-admin#139]
Hi there!

Is there a process for applying this admin panel to an existing API? Seems like you could relatively easily generate the specific model ng-modules based on lb-services.

**Comment by n8stowell82** [comment]
+1 for this.  I have been eying this project for awhile now trying to figure out if I can apply it to a pre built and fully functional api.  What I have been looking for is a django style admin generator for loopback

**Comment by beeman** [comment]
At this moment this project is not directly suitable to do this. You can probably replace this API with your existing one and modify the client to work with those models, but it currently is a manual process. 

Eventually the idea is to have generators that can help you with that. In the mean time I suggest you to look at a project like [BoLaMN/loopback-component-admin](https://github.com/BoLaMN/loopback-component-admin), which is a plug-and-play admin component.

**Comment by ianseyer** [comment]
Wait, I want to make sure that I am understanding this correctly:

this admin backend was designed specifically for a specific set of models?

**Comment by beeman** [comment]
It's designed to be a base that is easily extended and it comes with a pre-defined set of models. 

In it's current state it's not a plug-and-play admin interface for each LoopBack API you connect it to.

**Comment by beeman** [comment]
Another tool that might be helpful is this generator [johannesjo/generator-angular-auto-admin-loopback](https://github.com/johannesjo/generator-angular-auto-admin-loopback).
