### ISSUE TITLE
Error: ENOENT errno 34

### ISSUE THREAD

**Issue by macbroadcast** [beeman/loopback-angular-admin#14]
hey there, i am exited about to install and i did everything like you discribed, test worked fine

Execution Time (2014-12-17 19:52:37 UTC)
jshint:all                 576ms  ▇ 3%
loopback_angular:services   2.2s  ▇▇▇▇ 11%
docular                     9.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 47%
wiredep:app                320ms  ▇ 2%
concurrent:dist             7.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇ 35%

but
/loopback-angular-admin/server# npm start  gave me an 

npm ERR! Error: ENOENT, open '/root/loopback-angular-admin/server/package.json'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Linux 3.13.0-37-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! cwd /root/loopback-angular-admin/server
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path /root/loopback-angular-admin/server/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 

Thanks for your help and your awsome work ! :+1:

**Comment by cristianquaglio** [comment]
hi everybody
can somebody help me?
I want to install loopback like the official site says
but that dont works for me
npm ERR! Additional logging details can be found in:
npm ERR! /home/usuario/npm-debug.log
npm ERR! not ok code 0
the directory have write permissions, what happs??
