### ISSUE TITLE
401 Error Over Proxy

### ISSUE THREAD

**Issue by denzelwamburu** [beeman/loopback-angular-admin#141]
Greetings,

Seems the API is not working when a machine is under proxy. 

Check the attached screenshot from Chrome Dev Tool.
![screenshot from 2015-10-26 17 04 11](https://cloud.githubusercontent.com/assets/6532631/10731573/20896a0e-7c07-11e5-84a2-2efde617700f.png)

**Comment by beeman** [comment]
@denzelwamburu This has probably to do with your proxy configuration that is proxying 0.0.0.0. Another option would be to set the API_URL as described in the README.
