### ISSUE TITLE
bower install && grunt build issue

### ISSUE THREAD

**Issue by richh93** [beeman/loopback-angular-admin#142]
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! loopback-angular-admin@0.1.1 postinstall: `bower install && grunt build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the loopback-angular-admin@0.1.1 postinstall script 'bower install && grunt build'.
npm ERR! This is most likely a problem with the loopback-angular-admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install && grunt build
npm ERR! You can get their info via:
npm ERR!     npm owner ls loopback-angular-admin
npm ERR! There is likely additional logging output above.

I'm on OS X El Capitan.

Thanks

**Comment by jhitchcock** [comment]
I have the same issue

**Comment by jhitchcock** [comment]
I eneded up getting it running by seperating out the commands and doing each with sudo and without : /

**Comment by denzelwamburu** [comment]
Actually running the commands differently works.

**Comment by jhitchcock** [comment]
Actually, I realized later on running it all together was maxing out my ram on a tiny cloud9 VM, and running them separate were not

**Comment by dev-augmenta** [comment]
I have the same issue, Could anyone please post the complete solution?
It's impossible to push updates to heroku...

**Comment by dev-augmenta** [comment]
my complete solution to push to heroku is here https://github.com/beeman/loopback-angular-admin/issues/156

to solve grunt problems just change postinstall command to

bower cache clean && bower install && grunt build

**Comment by beeman** [comment]
The one-line install mentioned in the readme should work on a machine with enough capabilitues. If not, please reopen the issue.
