### ISSUE TITLE
Can the build tool grunt be changed to gulp

### ISSUE THREAD

**Issue by LS1231** [beeman/loopback-angular-admin#144]

**Comment by beeman** [comment]
It wil eventually use gulp, but there is not timeframe for that yet. There is an issue for it here https://github.com/beeman/loopback-angular-admin/issues/129.

If you want to use it, look at what @movibe has done in here: https://github.com/beeman/loopback-angular-admin/pull/137

Remember that his version is not supported by me and does not update with this project.
