### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by bosco-li** [beeman/loopback-angular-admin#149]
Hi there, is there information on how to get started with our own models after we've installed the packages?  

I'm thinking to install, replace the model and do a build.. but not sure if that's the right approach, also I'm not sure which models we can remove and which one needs to be there too.  Please help.

Thanks for the help.

**Comment by beeman** [comment]
Hi @bosco-li , there is currently no actual workflow for how to extend the application. 

You can add the models that you need and copy and refactor an angular module to suit your needs.

The models `category`, `event`, `note`, `page`, `post` and `product` can be disabled with out too much effort. 

I hope this helps.
