### ISSUE TITLE
 possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners()

### ISSUE THREAD

**Issue by lsfzheng** [beeman/loopback-angular-admin#150]
I install many times,but can't run success
Can open login page,but can't login in

**Comment by emilianox** [comment]
+1 but the login work

**Comment by xapou** [comment]
I fixed it in ```server/boot/99-fake-data.js``` by replacing:

```javascript
    for (var model in structure) {
      var options = structure[model];
      log('Creating %s items for model %s', options.count, model);
      for (var i = 0; i < options.count; i++) {
        promises.push(app.models[model].createFakeData(faker));
      }
    }
```
by this:

```javascript
  if(app.dataSources.db.connected) {
    createFakeData();
  } else {
    app.dataSources.db.once('connected', createFakeData);
  }

  function createFakeData() {
    for (var model in structure) {
      var options = structure[model];
      log('Creating %s items for model %s', options.count, model);
      for (var i = 0; i < options.count; i++) {
        promises.push(app.models[model].createFakeData(faker));
      }
    }
  }
```

**Comment by OwenBrotherwood** [comment]
I have the warning
http://stackoverflow.com/questions/9768444/possible-eventemitter-memory-leak-detected 

At the moment, I cannot login but that could be another problem.

@xapou "fixed" something: not sure if it was the warning or the original issue statement, cannot login

**Comment by OwenBrotherwood** [comment]
possible EventEmitter memory leak detected. 11 connected listeners added. Use emitter.setMaxListeners()
http://stackoverflow.com/questions/9768444/possible-eventemitter-memory-leak-detected

Some loopback issue???
Patch === no warning in node_modules lib for loopback
EventEmitter.setMaxListeners(0);

Todo: google in loopbacks issues.

../node_modules/loopback-datasource-juggler/lib/datasource.js
```
/*!
 * Module dependencies
 */
var ModelBuilder = require('./model-builder.js').ModelBuilder;
var ModelDefinition = require('./model-definition.js');
var RelationDefinition = require('./relation-definition.js');
var OberserverMixin = require('./observer');
var jutil = require('./jutil');
var utils = require('./utils');
var ModelBaseClass = require('./model.js');
var DataAccessObject = require('./dao.js');
var defineScope = require('./scope.js').defineScope;
var EventEmitter = require('events').EventEmitter;
var util = require('util');
var assert = require('assert');
var async = require('async');
var traverse = require('traverse');


EventEmitter.setMaxListeners(0);
```

**Comment by denzelwamburu** [comment]
Facing the same issue.

**Comment by dev-augmenta** [comment]
Look at my answer https://github.com/beeman/loopback-angular-admin/issues/156
I had the same problem and I had to change the session storage engine to Mongo

**Comment by beeman** [comment]
I've implemented the change that @xapou suggested in this commit https://github.com/beeman/loopback-angular-admin/commit/139d199c0be0503aa047d0e1c63d9cf916e987bb.

Please reopen the issue if it did not fix it.

**Comment by lehni** [comment]
For those looking for a solution to this LoopBack issue. When writing async code, during auto-migration, data-sources will observe as many 'connected' events as there are models.

Here a simple solution to prevent the error while still having a reasonable value for the maximum of listeners:

```js
const numModels = Object.keys(app.models).length
for (let dataSource of Object.values(app.dataSources)) {
  dataSource.setMaxListeners(numModels)
}
```
