### ISSUE TITLE
Strongloop arc cannot view model

### ISSUE THREAD

**Issue by hoangtrongphuc** [beeman/loopback-angular-admin#167]
when i run : slc arc, web browser open new tab of strongloop arc, but i can not see any model though mongodb is running

**Comment by beeman** [comment]
@hoangtrongphuc Thanks for creating this issue. This should work again with the latest master, thanks to the solution I found here: https://github.com/strongloop/strong-arc/issues/900

Can you please try it?

**Comment by hoangtrongphuc** [comment]
Yes, i tried and it's worked fine. Thank you
