### ISSUE TITLE
Failed to deploy at google cloud by console command "gcloud preview app deploy"

### ISSUE THREAD

**Issue by amiashraf** [beeman/loopback-angular-admin#170]
Hi there,
I have developed my loopback app and was going to deploy at google cloud platform with gcloud sdk console. At the time of deploy I am facing following error. Is there any one who can help me about?
```
Beginning teardown of remote build environment (this may take a few seconds).
ERROR: (gcloud.preview.app.deploy) Docker build aborted: The command [/bin/sh -c npm install --unsafe-perm ||   ((if [ -f npm-debug.log ]; then       cat npm-debug.log;     fi) && false)] returned a non-zero code: 1
```
**Note: the same issue is appearing with fresh git clone.**

**Comment by beeman** [comment]
Hi @amiashraf , can you check if you have the same issues with this project? https://github.com/strongloop/loopback-sandbox
