### ISSUE TITLE
Implement flow for password recovery, changing password, use passport local strategy

### ISSUE THREAD

**Issue by PhilippeCorreges** [beeman/loopback-angular-admin#173]
Hi !
A useful feature would be to integrate the workflows for password recovery, change password ad verified password as given by strongloop for passport local strategy.

Thanks for the great job!

Philippe

**Comment by beeman** [comment]
Hi @PhilippeCorreges, yes this would be absolutely welcome. At work we've created a password recovery flow, I will try to see if I can port that functionality to this app. 

I haven't looked into the passport strategy, a PR for that is welcome.

**Comment by beeman** [comment]
This issue is created for the `v0.x` version of the project, which is no longer support nor maintained as of January 16th 2017. I'm therefore closing this issue.

All development effort will be put in the new version of the project that is named Colmena CMS.
