### ISSUE TITLE
Passport LDAP

### ISSUE THREAD

**Issue by amirtasleem** [beeman/loopback-angular-admin#177]
Hi @beeman, firstly thanks for the great job! I was trying to connect to LDAP but the social login gives the error 
Loopback
404 Error: Cannot GET /auth/msad
   at raiseUrlNotFoundError (D:\inetpub\wwwroot\development\CapEx\node_modules\loopback\server\middleware\url-not-found.js:15:17)
   at Layer.handle [as handle_request] ...

p.s. providers.json settings are tested in @OwenBrotherwood loopback-example-passport and was wokring. 

your help is highly appreciated. 

Thanks

**Comment by beeman** [comment]
Hi @amirtasleem ,

I haven't tried this yet, but did you install the `passport-ldapauth` package?

**Comment by amirtasleem** [comment]
Hi @beeman thanks of the reply I have managed to get that sorted by reinstalling the package. 
Many Thanks.

**Comment by beeman** [comment]
That's good to hear! Good luck!
