### ISSUE TITLE
Failed when use the deploy to heroku function in the github project main page

### ISSUE THREAD

**Issue by ulion** [beeman/loopback-angular-admin#18]
the last error message is:

       jquery#2.1.3 client/app/bower_components/jquery
       
       ionicons#1.5.2 client/app/bower_components/ionicons
       [31m>> [39mLocal Npm module "grunt-angular-gettext" not found. Is it installed?
       [31m>> [39mLocal Npm module "grunt-angular-gettext" not found. Is it installed?
       [31m>> [39mLocal Npm module "grunt-include-source" not found. Is it installed?
       [33mWarning: Task "includeSource:server" not found. Use --force to continue.[39m
       
       [31mAborted due to warnings.[39m

**Comment by beeman** [comment]
There where some packages missing from the package.json file. 

The issue now is that grunt-include-source does not include the right Javascript files, i'm working on it!

**Comment by beeman** [comment]
Took some work but it looks like it's working again now :)

**Comment by movibe** [comment]
Deploy in Heroku, the last version https://admin-io.herokuapp.com/

**Comment by ulion** [comment]
Great, thank you!

2015-01-17 10:03 GMT+08:00 Willian Ribeiro Angelo <notifications@github.com>
:

> Deploy in Heroku, the last version https://admin-io.herokuapp.com/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beeman/loopback-angular-admin/issues/18#issuecomment-70349917>
> .
>



-- 
Ulion

**Comment by movibe** [comment]
Close Issue?
