### ISSUE TITLE
Create a generator for the front end modules 

### ISSUE THREAD

**Issue by shalkam** [beeman/loopback-angular-admin#180]
Hi,
I just wanted to know if there is a specific generator has been used for the angular modules here.

Thanks.

**Comment by beeman** [comment]
Hi @shalkam,

In the beginning of the project I used [generator-angular](https://www.npmjs.org/package/generator-angular). The angular modules have changed a lot though, to it's no longer compatible, as stated in the README.

I'm working on an enhanced version in the [develop branch](https://github.com/beeman/loopback-angular-admin/tree/develop), and I think it will be a nice addition to have generators for that structure.

Related: #171  #151 #139

**Comment by beeman** [comment]
This issue is created for the `v0.x` version of the project, which is no longer support nor maintained as of January 16th 2017. I'm therefore closing this issue.

All development effort will be put in the new version of the project that is named Colmena CMS.
