### ISSUE TITLE
side menu

### ISSUE THREAD

**Issue by mpavlidis** [beeman/loopback-angular-admin#182]
i want to ask how can i add a new tab on the left menu ??
for example we have events and i want to create events2.

thanks

**Comment by whispers16** [comment]
in every module folder there's another config folder, and inside there's a .config.js
and you can see in the first lines the way to add a new menu (with the $rootScope), for example:

`$rootScope.addMenu(gettextCatalog.getString('events2'), 'app.events.events2', 'fa-calendar');`

Hope that helps!

**Comment by beeman** [comment]
This issue is created for the `v0.x` version of the project, which is no longer support nor maintained as of January 16th 2017. I'm therefore closing this issue.

All development effort will be put in the new version of the project that is named Colmena CMS.
