### ISSUE TITLE
New possible feature

### ISSUE THREAD

**Issue by PhilippeCorreges** [beeman/loopback-angular-admin#183]
Hello,

A new possible feature would be to have the client side in angular2 since the releases are stable now.

Thanks

**Comment by beeman** [comment]
This issue is created for the `v0.x` version of the project, which is no longer support nor maintained as of January 16th 2017. I'm therefore closing this issue.

All development effort will be put in the new version of the project that is named Colmena CMS.

**Comment by beeman** [comment]
Btw, Colmena CMS will be using Angular 2 :)
