### ISSUE TITLE
API Check

### ISSUE THREAD

**Issue by PhilippeCorreges** [beeman/loopback-angular-admin#185]
Hello,
My server is checking for online APIs with the following message : 
![capture d ecran 2016-06-20 a 13 13 46](https://cloud.githubusercontent.com/assets/11230777/16192312/dac11fc4-36e8-11e6-9b33-476642ec2fd2.png)

Any idea where I could prevent API test before loading and also changing the path for /containers/files ?

I ran over the code and still have no clue.

Thanks and Regards,

**Comment by dmastag** [comment]
Just a guess here, but has the database been created and loopback connector been installed?

**Comment by PhilippeCorreges** [comment]
In fact, I was just stating the server with a npm start ... whilst gulp must be used here.
Gulp serve solves the issue.
