### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by PhilippeCorreges** [beeman/loopback-angular-admin#186]
Hi Beeman.

**Tested on Safari only** : If cookies are set to blocked, an error is thrown :
SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.
It does exist a webkit issue raised on it : https://bugs.webkit.org/show_bug.cgi?id=137760

So maybe the app should show a warning on not using cookies on "certain browsers." :)

Best,

Philippe

**Comment by beeman** [comment]
This issue is created for the `v0.x` version of the project, which is no longer support nor maintained as of January 16th 2017. I'm therefore closing this issue.

All development effort will be put in the new version of the project that is named Colmena CMS.
