### ISSUE TITLE
properties的List能否支持

### ISSUE THREAD

**Issue by hxliujing** [beeman/loopback-angular-admin#188]
现在好像只支持单个k,v 操作
不支持properties的List或Map操作

**Comment by beeman** [comment]
Hi @hxliujing can you please submit the issue in English?

**Comment by taoyuan** [comment]
@beeman @hxliujing means that can loopback-angular-admin support `List` or `Map` type properties?

**Comment by beeman** [comment]
This issue is created for the `v0.x` version of the project, which is no longer support nor maintained as of January 16th 2017. I'm therefore closing this issue.

All development effort will be put in the new version of the project that is named Colmena CMS.
