### ISSUE TITLE
Any datatable integration?

### ISSUE THREAD

**Issue by ulion** [beeman/loopback-angular-admin#19]
As an admin ui, data table is a required feature, is there any integration?

**Comment by beeman** [comment]
Good point, i'll start integrating [ng-grid](http://angular-ui.github.io/ng-grid/) right away!

**Comment by beeman** [comment]
Or rather it's successor [ui-grid](http://ui-grid.info/) :)

**Comment by ulion** [comment]
I noticed ng-admin has good datatable integration, you may check it.

2015-01-15 21:16 GMT+08:00 Bram Borggreve <notifications@github.com>:

> Or rather it's successor ui-grid <http://ui-grid.info/> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/beeman/loopback-angular-admin/issues/19#issuecomment-70083801>
> .
>



-- 
Ulion

**Comment by beeman** [comment]
It looks like ng-admin has a custom-made solution so I went for the ui-grid option. 

Just implemented it, I have a demo in the Sandbox :)
