### ISSUE TITLE
When the error will be logged in

### ISSUE THREAD

**Issue by Royweb** [beeman/loopback-angular-admin#192]
I have problems when the application live, there are error messages like this, if anyone can help me

![screenshot from 2016-09-29 13-52-36](https://cloud.githubusercontent.com/assets/10422337/18943801/060b3e32-864c-11e6-914f-9015f5d1c447.png)

**Comment by beeman** [comment]
This issue is created for the `v0.x` version of the project, which is no longer support nor maintained as of January 16th 2017. I'm therefore closing this issue.

All development effort will be put in the new version of the project that is named Colmena CMS.
