### ISSUE TITLE
How I can manually create the modules?

### ISSUE THREAD

**Issue by molinojopiento** [beeman/loopback-angular-admin#193]
Is there any tutorial ?, because copy and paste a module, but not seen in the lateral menu.

Please help me. Thanks! 💃

**Comment by KratiChauhan** [comment]
Not working for me as well....waiting for a solution

**Comment by beeman** [comment]
This issue is created for the `v0.x` version of the project, which is no longer support nor maintained as of January 16th 2017. I'm therefore closing this issue.

All development effort will be put in the new version of the project that is named Colmena CMS.
