### ISSUE TITLE
Error while running...

### ISSUE THREAD

**Issue by lealexandre** [beeman/loopback-angular-admin#195]
Hi,

After installing the script without any issues, I tried to run it. But I got a blank screen and got this error in the console:

> Uncaught Error: [$injector:modulerr] Failed to instantiate module loopbackApp due to:
> Error: [$injector:modulerr] Failed to instantiate module config due to:
> Error: [$injector:nomod] Module 'config' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

I believe the error is from this file: index.html

Does anyone have any suggestions?

Thanks

Alexandre

**Comment by beeman** [comment]
This issue is created for the `v0.x` version of the project, which is no longer support nor maintained as of January 16th 2017. I'm therefore closing this issue.

All development effort will be put in the new version of the project that is named Colmena CMS.
