### ISSUE TITLE
How to run client without Grunt serve?

### ISSUE THREAD

**Issue by n8stowell82** [beeman/loopback-angular-admin#196]
Hello, first off this app is a lifesaver.  I have been able to rapidly build out my own app and have been able to do with very little problems.  I am at the point where I am trying to deploy this app to another server, but am completely stuck.  I can run "grunt serve" fine, and the app will run, but what I need is to serve the app without grunt.  This app will be deployed to a windows server machine and I need to be able to install the app as service.  I can successfully do this with the api portion and navigate to /explorer/ or just /api/ and things work.  However, when trying to navigate to the client, the whole thing falls apart.  Any ideas on how to get the client to run without needing to run grunt serve (grunt build is ok as it can run once and be left alone)

Thanks in advance for your help

**Comment by KratiChauhan** [comment]
Hey...can you help me getting ramped up to this tool for building app...i need to as well build apps but am stucked and documentation provided is not enough for a novice like me. A quick steps on how to define my database, models and app will be very useful

**Comment by beeman** [comment]
This issue is created for the `v0.x` version of the project, which is no longer support nor maintained as of January 16th 2017. I'm therefore closing this issue.

All development effort will be put in the new version of the project that is named Colmena CMS.
