### ISSUE TITLE
[HELP] Project Purpose

### ISSUE THREAD

**Issue by KratiChauhan** [beeman/loopback-angular-admin#198]
Hello 

i am exploring your project as we have a need to create UI for loopback admin. But i am not able to understand the purpose of this project. Will this help me to 
1. Create a new loopback project from scratch ? 
2. Allow me to manage the existing / new created loopback project (created from command prompt) , if yes, then what all can I do in this ?

**Comment by beeman** [comment]
Hi @KratiChauhan,

The project is meant as a starter to build your own projects. It will not help you in building a project from scratch. It comes with a couple of models and interfaces for those models, and you can adjust them to your needs.

You can hook it up to an existing loopback api, and then add the modules you need to the frontend.

**Comment by beeman** [comment]
This issue is created for the `v0.x` version of the project, which is no longer support nor maintained as of January 16th 2017. I'm therefore closing this issue.

All development effort will be put in the new version of the project that is named Colmena CMS.
