### ISSUE TITLE
nodemailer.?

### ISSUE THREAD

**Issue by suriyaJaay** [beeman/loopback-angular-admin#199]
its really awesome to work with it. well it could be better if it has contact list, with that one can able to send mail(with customized or inbuilt template) to selected contacts from list or all contacts from the list with nodemailer.!!!

**Comment by KratiChauhan** [comment]
Hi SuriyaJaay 

Can you help me understand the purpose of this project and how can we customize it ?

**Comment by beeman** [comment]
Hi @suriyaJaay,

While I understand why this would be nice to have, I currently have no plans to further extend the functionality of the app.

The first things I will work on are a rewrite of the UI in Angular 2. After that I will add support for Loopback 3.
