### ISSUE TITLE
error when running grunt 

### ISSUE THREAD

**Issue by raymatos** [beeman/loopback-angular-admin#200]
```Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
(node:23127) DeprecationWarning: sys is deprecated. Use util instead.
```

using node 7.0.0

**Comment by beeman** [comment]
This issue is created for the `v0.x` version of the project, which is no longer support nor maintained as of January 16th 2017. I'm therefore closing this issue.

All development effort will be put in the new version of the project that is named Colmena CMS.
