### ISSUE TITLE
Migrate to Angular2

### ISSUE THREAD

**Issue by suryakand** [beeman/loopback-angular-admin#202]
I have been playing with Angular2 Loopback SDK (have a look at):
https://loopback.io/doc/en/lb2/Angular-2-SDK.html
https://github.com/mean-expert-official/loopback-sdk-builder

It looks very promising. This gives us all benefits of typescript and Angular2.

**Comment by beeman** [comment]
Hi @suryakand, thanks for you message. 

Good question. I have been playing too with the great loopback-sdk-builder and as we speak I'm working on a re-write of this project using Angular 2. 

The last 2 days I've been testing if LoopBack 3 would be a good fit but I decided to keep it with LoopBack 2 at this point, as a there are a lot of mixins for version 2 that I'd like to include.

I'll post more information in this topic once I have something that it workable.

**Comment by suryakand** [comment]
Thanks @beeman 
I'll be happy to contribute if you need another helping hand.

**Comment by beeman** [comment]
I made the project public and opened issue #204 to track it's progress.
