### ISSUE TITLE
Grunt build fails with MySQL datasource

### ISSUE THREAD

**Issue by bhayla** [beeman/loopback-angular-admin#203]
Grunt build fails when i added mySql datasource

  "mysqldb": {
    "host": "localhost",
    "port": 3306,
    "database": "project",
    "username": "admin",
    "password": "****",
    "name": "mysqldb",
    "connector": "mysql"
  }

unclear why this is happening?? the datasource configuration work on loopback datasource example  https://github.com/strongloop/loopback-example-database

![image](https://cloud.githubusercontent.com/assets/9060700/21582910/0be72e4c-d061-11e6-88ee-05d42e100e7d.png)

**Comment by beeman** [comment]
This issue is created for the `v0.x` version of the project, which is no longer support nor maintained as of January 16th 2017. I'm therefore closing this issue.

All development effort will be put in the new version of the project that is named Colmena CMS.
