### ISSUE TITLE
open

### ISSUE THREAD

**Issue by htkv** [beeman/loopback-angular-admin#210]
sir how to open this template in my browser 
actualy ,i have download this template and put my xampp server's htdocs folder like -
xampp/htdocs/loopback-angular-admin

but now problem is that which file open in browser that cauld show main page of admin

**Comment by beeman** [comment]
@htkv this project is not just a template you put in your server, it's a project that you need to build and run using the Loopback server that comes with it. 

Please read the project README to get a better understanding of how this works.

I hope this answers your question.
