### ISSUE TITLE
when does it support LB3.0

### ISSUE THREAD

**Issue by jjhesk** [beeman/loopback-angular-admin#211]
I have an existing Lb using the latest 3.0 as framework. Is this compatible to lb3.0?

**Comment by beeman** [comment]
Hi @jjhesk,

As you can read in the announcement of the new version, LB3 will not yet be supported:

https://github.com/beeman/loopback-angular-admin/issues/204

Once the new version is out I will explore what needs to be done to support LB3 and to see if it's possible to support both.

That being said, the admin interface has nothing that is tied to LB2 so it might just work, but at this moment I won't support LB3.

I hope this answers your question.

**Comment by beeman** [comment]
For anyone reading this issue, since a few weeks Colmena runs on LoopBack v3.
