### ISSUE TITLE
Add vagrant?

### ISSUE THREAD

**Issue by movibe** [beeman/loopback-angular-admin#25]
I found these links to test and add to the project, but I'm not the vagrant on my mac, does anyone could test and post to merge?

https://github.com/illuminatedweb/vagrant-loopback

https://github.com/nickleus73/vagrant-loopback-ubuntu-14-04

**Comment by beeman** [comment]
Great! I'm working on Vagrant support as we speak, I will look at this links too!  :)

**Comment by beeman** [comment]
I've started this [branch](https://github.com/beeman/loopback-angular-admin/tree/feature/vagrant). It's not completely working yet, but the start is here.
