### ISSUE TITLE
bug: npm run initdb broken

### ISSUE THREAD

**Issue by dmtw** [beeman/loopback-angular-admin#286]
### Bug or feature request

- [ x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
`npm run initdb`
produces this error after latest changes to `colmena/packages/api-helpers/src/helpers.js`:
`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'create' of undefined`.

### Additional information (OS, Node.js version, etc)
npm 4.2.0
linux x64 7.10.0

**Comment by beeman** [comment]
Hi @dmtw, thanks for taking the time to create the issue.

I confirmed the bug, the sample data in the new `api-dev` module referenced a wrong, non-existing model.

I fixed the sample data and updated the sample data code to show a warning instead of an unhandled error.
