### ISSUE TITLE
API Crashes When Updating a User's Password as Admin

### ISSUE THREAD

**Issue by bartshappee** [beeman/loopback-angular-admin#338]
### Bug or feature request

- [X] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

Cloned the repo & install everything
Setup local mongodb & initdb
npm run dev
Login as admin
Try and change manager@example.com password to manager

### Link to sample repo to reproduce issue (if bug)

https://github.com/colmena/colmena 

### Expected result

The password to update or at least no crash

### Actual result (if bug)

Crash

### Additional information (OS, Node.js version, etc)

$ npm -v => 5.5.1
$ node -e 'console.log(process.platform, process.arch, process.versions.node)' => darwin x64 6.9.5

**Comment by beeman** [comment]
Hi @bartshappee 

This should not be the case! 

I can't seem to reproduce the issue though. Could you please paste the error message you get?

**Comment by bartshappee** [comment]
Newest version doesn't seem to have the issue
Although looking at the printed message when I reset the manager's password (http://127.0.0.1:9000/#/password-reset?token=8367864a-4516-4bad-bb18-b26f88832f29) the page loaded but nothing happend when I tried to reset the password
