### ISSUE TITLE
up file error

### ISSUE THREAD

**Issue by vdphuong** [beeman/loopback-angular-admin#34]
events.js:72
        throw er; // Unhandled 'error' event

**Comment by beeman** [comment]
Hi @vdphuong,

Could you please send some more info on how to reproduce this error? 

In the main project there is not a file called events.js, so i'm curious where the error comes from.

Thanks in advance!

**Comment by vdphuong** [comment]
Thank you for viewing my posts!
I figured out the cause
folder Strong in your example lack of File folder

**Comment by beeman** [comment]
Thanks, i've added the folder to the project!

https://github.com/beeman/loopback-angular-admin/commit/b2d87a3e0f158a5863f2edd5d211dccb94da194a
