### ISSUE TITLE
Angular Submodule Generator

### ISSUE THREAD

**Issue by tamitutor** [beeman/loopback-angular-admin#35]
Greetings,

This is an extremely helpful project to get a workflow going for an enterprisey, full-stack app.  Thank you very much for making it publicly accessible!

However, based on the architectural layout and design of the Angular.js portion, I'm left with a lingering question:
Did you use a yeoman generator for your Angular.js submodules, and if so what did you use?  

I cannot find any documentation in the generator-angular app about submodules so I'm assuming you used something different?

I've found https://github.com/cgross/generator-cg-angular.  It looks helpful...but I just wanted to get a more detailed peak into your development workflow.

Thanks in advance,

Tami

**Comment by beeman** [comment]
Hi Tami,

Thanks for your kind words regarding this project, I'm glad to hear that it is useful for you! :)

I indeed started with the generator-angular generator, but thanks to @movibe the project now has a different structure.

The modules are way better structured now, the only downside is that the generator stopped working.

It would be great to have a generator that works with this project, I guess it will be possible to refactor the one you mentioned. I've never looked at how the generators work so it will take some time to investigate on this.

Regards, 

Bram

**Comment by tamitutor** [comment]
Hi @beeman,

Thank you for your helpful feedback.  In order to duplicate the elegant structure you have here, I'm actually thinking a grunt task could do it--for now.  It is more of a hack than a long-time solution (ie. generator) but it will utilize the following:

1. Utilize a command line call to execute the Mean.js AngularJS Module Sub-Generator (@http://meanjs.org/generator.html#angular-module).
2.  And another command line call to "cp" or "mv" the generated files to the app path defined in bower.json.

If it ends up being helpful to me in any way I will put it into a github.com repo and share the link here.

Thanks!
