### ISSUE TITLE
"npm run dev" now broken on clean run

### ISSUE THREAD

**Issue by bartshappee** [beeman/loopback-angular-admin#362]
### Bug or feature request
- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

Can't start colmena after conversion to typescript

git clone https://github.com/colmena/colmena
npm install
lerna boostrap
npm run dev

### Link to sample repo to reproduce issue (if bug)

base repo

### Expected result

Launch colmena

### Actual result (if bug)
...
@colmena/colmena: @colmena/api: [nodemon] 1.11.0
@colmena/colmena: @colmena/api: [nodemon] to restart at any time, enter `rs`
@colmena/colmena: @colmena/api: [nodemon] watching: *.*
@colmena/colmena: @colmena/api: [nodemon] starting `node server/server.js`
@colmena/colmena: @colmena/api: [nodemon] app crashed - waiting for file changes before starting...
@colmena/colmena: @colmena/api: module.js:471\n    throw err;\n    ^
@colmena/colmena: @colmena/api: Error: Cannot find module '<path>/colmena/apps/api/server/server.js'\n    at Function.Module._resolveFilename (module.js:469:15)\n    at Function.Module._load (module.js:417:25)\n    at Module.runMain (module.js:604:10)\n    at run (bootstrap_node.js:394:7)\n    at startup (bootstrap_node.js:149:9)\n    at bootstrap_node.js:509:3

### Additional information (OS, Node.js version, etc)

OsX
$ npm -v 5.5.1
$ node -e 'console.log(process.platform, process.arch, process.versions.node)' darwin x64 6.9.5

**Comment by beeman** [comment]
Hi @bartshappee 

Thanks a lot for taking the time to create this issue! 

It should have been fixed in the `develop` branch, could you please verify?

Thanks! 👍

**Comment by bartshappee** [comment]
Verified
