### ISSUE TITLE
Dependencies are deprecated

### ISSUE THREAD

**Issue by rluvaton** [beeman/loopback-angular-admin#365]
### Bug or feature request
Dependencies are deprecated

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
just clone the repo
`git clone https://github.com/colmena/colmena.git colmena`

### Link to sample repo to reproduce issue (if bug)
https://github.com/colmena/colmena.git

### Expected result
without deprecated dependencies

### Actual result (if bug)
```
npm WARN deprecated nsp@2.7.0: The Node Security Platform service is shutting down 9/30 - https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting
npm WARN deprecated ejs@1.0.0: Critical security bugs fixed in 2.5.5
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated swagger-ui@2.2.10: No longer maintained, please upgrade to swagger-ui@3.
npm WARN deprecated gcloud@0.10.0: gcloud has been renamed to google-cloud. To get new features and bug fixes, you must use the new package.
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
```

### Additional information (OS, Node.js version, etc)

- NPM Version: **6.3.0**
- process.platform: **win32**
- process.arch:  **x64**
- process.versions.node: **8.9.0**

**Comment by beeman** [comment]
Hi @rluvaton , as you can read in [this comment](https://github.com/colmena/colmena/issues/364#issuecomment-382581859) the project is currently not being maintained. 

I will add a bigger notice to inform the users about this.
