### ISSUE TITLE
Question: start version of grunt file

### ISSUE THREAD

**Issue by paulvanbladel** [beeman/loopback-angular-admin#39]
I'm wondering, is there a specific version of the grunt file that you took as 'start' and on which you added e.g. the lb-services generation grunt task or did you design the gruntfile completely from scratch ?

**Comment by beeman** [comment]
The initial version of the Gruntfile is based on the angular-generator.

It has since been enhanced with the specific requirements of this project.

**Comment by paulvanbladel** [comment]
thanks Bram !
