### ISSUE TITLE
Logout session is not working...

### ISSUE THREAD

**Issue by gowram** [beeman/loopback-angular-admin#42]
when i tried logout and pressed back button, i still have have access to previous session, it seems that session is not deleted...

Regards
Rama.

**Comment by beeman** [comment]
@movibe do you have time to check out this issue? :) If not, i'll take a look at it!

**Comment by movibe** [comment]
Yes @beeman , I will send new fixes and a new module chat with socket.io for you to analyze

**Comment by beeman** [comment]
Awesome @movibe , really looking forward to that!  Could you send it in two separate branches?

**Comment by movibe** [comment]
Yes! @beeman :-)

**Comment by beeman** [comment]
@gowram could you check if #43 fixed this?

**Comment by gowram** [comment]
Thanks guys it working fine right now..
thanks for your quick fix.
