### ISSUE TITLE
acls

### ISSUE THREAD

**Issue by vdphuong** [beeman/loopback-angular-admin#46]
i chage acls in event.json file to: 

{
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW"
    },
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW"
    }

after login http://localhost:3333/#/login with username and password 
http://localhost:3333/#/app/events -> 0k.
http://localhost:3333/api/events ->

{"error":{"name":"Error","status":401,"message":"Authorization Required","statusCode":401,"code":"AUTHORIZATION_REQUIRED","stack":"Error: Authorization Required\n    at C:\\Users\\VDP\\Desktop\\admin\\node_modules\\loopback\\lib\\application.js:344:21\n    at C:\\Users\\VDP\\Desktop\\admin\\node_modules\\loopback\\lib\\model.js:295:5\n    at C:\\Users\\VDP\\Desktop\\admin\\node_modules\\loopback\\common\\models\\acl.js:437:23\n    at C:\\Users\\VDP\\Desktop\\admin\\node_modules\\async\\lib\\async.js:254:17\n    at done (C:\\Users\\VDP\\Desktop\\admin\\node_modules\\async\\lib\\async.js:135:19)\n    at C:\\Users\\VDP\\Desktop\\admin\\node_modules\\async\\lib\\async.js:32:16\n    at C:\\Users\\VDP\\Desktop\\admin\\node_modules\\async\\lib\\async.js:251:21\n    at C:\\Users\\VDP\\Desktop\\admin\\node_modules\\async\\lib\\async.js:575:34\n    at C:\\Users\\VDP\\Desktop\\admin\\node_modules\\loopback\\common\\models\\acl.js:420:17\n    at C:\\Users\\VDP\\Desktop\\admin\\node_modules\\loopback\\common\\models\\role.js:207:21"}}

**Comment by brunocascio** [comment]
+1

**Comment by beeman** [comment]
I'm closing it now because ACL's are not yet implemented in this project.

For general questions about LoopBack I recommend you to go to one of these gitter rooms and ask there:

https://gitter.im/strongloop/loopback
https://gitter.im/loopbackers/loopbackers.github.io

If it is a bug that is only in this project please reopen this issue.
