### ISSUE TITLE
Deployment script for Amazon EC2 

### ISSUE THREAD

**Issue by sfakir** [beeman/loopback-angular-admin#47]
Hi,
would be awesome if there is a single Amazon EC2 Installation and Deployment script.

(maybe even push the Assets to S3 instead of putting it on the server.)

**Comment by beeman** [comment]
Hi @sfakir ,

I'd love to have this added in the project too, but as I'm not using EC2 myself it has no priority for me at the moment.

Feel free to send a pull request that implements it. I'll happily test and merge it if it works!
