### ISSUE TITLE
Idea: sails as backend

### ISSUE THREAD

**Issue by paulvanbladel** [beeman/loopback-angular-admin#51]
Bram,

Did you ever consider using Sails as backend ? http://sailsjs.org/
I like loopback but I feel more attracted to sailsJS, which is real convention over configuration.
SailsJS = keep it simple. Loopback not always :)

**Comment by macbroadcast** [comment]
Loopback is the future , sails is just a trend, so keep everything like it is ;) cheers

**Comment by beeman** [comment]
Hi Paul,

I have looked at Sails too but personally I prefer Loopback.

The things that I like about it include the ability to connect to other REST API's natively, the integration with AngularJS feels like magic, there are some powerful integrations like the file upload and e-mail.

Sails includes stuff like server side rendering which to me is unneeded. 

The thing that I do like about Sails is the websocket integration, but it's not a big enough selling point.

I'm curious to see how a fork with Sails would look like, but it's not likely that I'll implement or merge it myself any time soon.

I hope this clears it up a bit :)

**Comment by paulvanbladel** [comment]
Hi Bram,
Very much appreciated learning your point of view on sailsJs.
Thanks
paul.
