### ISSUE TITLE
is there any update on using angular-formly 3.1.0

### ISSUE THREAD

**Issue by gowram** [beeman/loopback-angular-admin#56]
I would like to know, are they any plans to upgrade angular-formly 3.1.0 implementation?

**Comment by beeman** [comment]
I might upgrade it or might start using [angular-schema-form](https://github.com/Textalk/angular-schema-form), which is used by another project I look at working on.

I will compare the two and pick the one that suits the project best.

**Comment by beeman** [comment]
I have decided to use angular-schema-form in the future, I'm not sure when though.

**Comment by beeman** [comment]
FYI, I've updated formly after all, it just landed in master :)
