### ISSUE TITLE
ACL Implementation

### ISSUE THREAD

**Issue by movibe** [beeman/loopback-angular-admin#58]
Hi @beeman , i found this project in a group of NodeJS Brazil on Facebook, it would be nice if we could make an example of you guys using the Loopback

http://jedireza.github.io/drywall/

**Comment by beeman** [comment]
Hi @movibe, it looks like this project is based on plain Express/MongoDB at the backend and Backbone in the frontend. That technology stack is too different to merge in this project.

**Comment by movibe** [comment]
In fact I would like your opinion of mounting the ACL inspired this project, if you find interesting copy the idea and use in our project?

**Comment by beeman** [comment]
Can you show me where the ACL is defined? 

For this project we will use the LoopBack method for ACL's, but some inspiration can be useful :)
