### ISSUE TITLE
Observations for README betterment

### ISSUE THREAD

**Issue by pulkitsinghal** [beeman/loopback-angular-admin#59]
1. Folks may not immediately realize that running `npm start & grunt serve` spits out a PID which they can use to kill the server side of things. And that the rest of the logs are about the deployment and we start watching the client for changes.
  1. For the first few minutes, users may find themselves scratching their heads after hitting `ctrl+c` and trying the same step again ... as to why the port is occupied.
  2. Depending on the scroll buffer on one's terminal window, they may have already lost the PID or simply may not know to go looking for it.
  3. Maybe some commonly agreed upon language for the README that is way *way* shorter than the essay I just wrote here ... can be coined?
2. Running `grunt serve` without installing nodemon first ... still kicks off the process regardless. Only this time there is no PID so it gets a bit arbitrary to go looking for a node process to kill. Now yes, the next thing one may do right away is `npm install -g nodemon` and then `grunt serve` again but the earlier command has taken up the port (which one assumes had just plain failed but such is not the case) and again users are briefly left wondering ... `what???`
  1. Umm, so maybe some language that says: even if `grunt serve` fails due to lack of `nodemon`, a process occupying the port has started and must be killed before using `grunt serve` again.

**Comment by srisub** [comment]
I ran into the running process issue as well. You can just kill the node process - pid can be figured out via command line (e.g. ps -ax | grep node) and to confirm you can correlate it with what you see in the Activity Monitor / task manager - see attached. 
![screenshot 2015-04-11 21 30 14](https://cloud.githubusercontent.com/assets/1392314/7104442/eea46f0a-e095-11e4-8e50-d6d6d34315df.png)

**Comment by beeman** [comment]
It would be best to have the `grunt serve` command start the API, for instance with [grunt-nodemon](https://github.com/ChrisWren/grunt-nodemon).

**Comment by beeman** [comment]
I have updated the project so it will automatically start the API when you start the project with `grunt serve` and updated the README accordingly.

Can you please confirm that this solves this issue @pulkitsinghal?

**Comment by pulkitsinghal** [comment]
Confirmed, its easier and quicker to use.
