### ISSUE TITLE
AdminLTE

### ISSUE THREAD

**Issue by rborn** [beeman/loopback-angular-admin#6]
Hi, 
I saw you want to change the template at a later stage.
What about this one? https://github.com/almasaeed2010/AdminLTE

Just an idea ;)
Thank you

**Comment by ulion** [comment]
where is the branch now?

**Comment by rborn** [comment]
Is the master I think

**Comment by ulion** [comment]
Oh, yes, it should be.

**Comment by beeman** [comment]
Yep, it's merged and deleted :)
