### ISSUE TITLE
Detect if API is online

### ISSUE THREAD

**Issue by pulkitsinghal** [beeman/loopback-angular-admin#61]
Saw this in the TODOs, did some research ... realized I wasn't up to finishing the task ... thought it might be useful to jot down any notes, doubts and open questions semi-permanently. They get a bit lost in gitter.

1) Should https://github.com/HubSpot/offline be written as an angular service and/or injected into `app.run` in a format that somewhat resembles: http://pterkildsen.com/2012/12/12/angularjs-tips-and-tricks-broadcast-online-and-offline-status/

2) Searching on `bower` registry for an already angular wrapped version of HubSpot/offline turns up the very same repo as mentioned above but I don't believe its angular ready so not sure what's going on there. May be a lapse in my understanding of angular?

3) This https://github.com/neoziro/angular-offline seems well rounded (README-wise) but I don't think it wraps the HubSpot library.

**Comment by beeman** [comment]
This should be fixed in master via #107 . Could you please verify this? 

It's not a fancy solution like HubSpot/offline but it does the job.

**Comment by pulkitsinghal** [comment]
@beeman - I started grunt serve, then logged into the app and then killed the grunt process ... but attempting to navigate around the app didn't provide any sort of disconnect indicator. Am I testing for the right thing here?

**Comment by beeman** [comment]
This issue is created for the `v0.x` version of the project, which is no longer support nor maintained as of January 16th 2017. I'm therefore closing this issue.

All development effort will be put in the new version of the project that is named Colmena CMS.
