### ISSUE TITLE
Dropdown for Category in Products

### ISSUE THREAD

**Issue by jaypatel512** [beeman/loopback-angular-admin#62]
As shown in the image below, in `Add/Edit Product` form, the category field is a textbox asking for ID. It would be amazing if there was a way to provide a drop down there. I think of this issue as an enhancement. Being new to Node, and specially loopback, I will try my best to come up with a solution, but any suggestions would be advisable.
 
![screen shot 2015-04-13 at 4 52 19 pm](https://cloud.githubusercontent.com/assets/1309895/7126253/7b4249e2-e1fd-11e4-81b5-7ed5b7532364.png)

**Comment by beeman** [comment]
This is something that needs be done. Most of the work would be on the Angular side. 

At first the form engine needs to be upgraded. 

After that the form needs to have a select box filled with the categories, and it needs to preselect the option that is selected (3 in the case of this screenshot).

The list of categories can be easily fetched from the LoopBack API.

I'll upgrade the form engine soon.

**Comment by beeman** [comment]
Fixed in master :)
