### ISSUE TITLE
grunt doesn't work

### ISSUE THREAD

**Issue by danyaegoist** [beeman/loopback-angular-admin#65]
this line doesn't work API_URL=http://0.0.0.0:3000/api grunt

**Comment by beeman** [comment]
Did you follow the instructions in the README?

Do you get an error message while trying? If so, what does it say?

**Comment by danyaegoist** [comment]
i dont have errors. Grunt doesn't chang url_api

2015-04-16 17:11 GMT+03:00 Bram Borggreve <notifications@github.com>:

**Comment by beeman** [comment]
What about `API_URL=http://0.0.0.0:3000/api grunt build`  of `API_URL=http://0.0.0.0:3000/api grunt serve` ?

**Comment by danyaegoist** [comment]
i build another ip


2015-04-16 17:15 GMT+03:00 Bram Borggreve <notifications@github.com>:

**Comment by danyaegoist** [comment]
in both

**Comment by beeman** [comment]
I'm not sure what the problem is here. Can you try to explain it in more detail?

**Comment by beeman** [comment]
I'm not sure what the problem is here. 

If you still have this problem please open a new issue with a more detailed description.
