### ISSUE TITLE
ui-router loop forever

### ISSUE THREAD

**Issue by Masatoshi** [beeman/loopback-angular-admin#67]
hi. If api is down, ui-router cause looping between "/login" and "/router".

client/app/modules/users/config/users.auth.js

    if (rejection.status === 0) {
            $location.path('/');  // it cause loop forever
            CoreService.toastError('Connection Refused',
              'The connection to the API is refused. Please verify that the API is running!'
            );
    }

**Comment by beeman** [comment]
This is a known issue. If you have a PR that fixes it I'm happy to look at and consider merging it.

**Comment by beeman** [comment]
Should be fixed once #61 get's implemented

**Comment by beeman** [comment]
This should be fixed in master via #107. Could you please verify this?

**Comment by asgeirbirkis** [comment]
Not that I'm the original reporter, but I had been dealing with the same issue. At least for me, with #107 merged, I get directed to an error page when api goes down, and don't get stuck in an infinite loop.

**Comment by beeman** [comment]
Thanks for confirming @asgeirbirkis !
