### ISSUE TITLE
Other user(s) password available to guest (user@user.com)

### ISSUE THREAD

**Issue by OwenBrotherwood** [beeman/loopback-angular-admin#70]
I found that, after I registered my own email, I could see my password as guest via the web interface.

Is this known?
If not, give me a pointer so I can see if I can make a PR.

Note: admin password is not shown if one is guest

**Comment by beeman** [comment]
Thanks for this message, fixed in ebec6228d26fc3aae723a2f28dd99ea9f7f247aa :)
