### ISSUE TITLE
User Register saves confirmpassword to the file (database)

### ISSUE THREAD

**Issue by LetsDoIt-** [beeman/loopback-angular-admin#71]
Hi,
I have activated file system to view the data
{
  "db": {
    "name": "db",
    "connector": "memory",
    "file" : "db.json"
  }
}

When I created a new user using the Register screen I noticed that the "confirmPassword" property of the form also gets persisted to the file. Also it is in the text format so I am pretty sure this shouldn't be present.

**Comment by russelldc** [comment]
In modules/users/controllers/register.ctrl.js, before the User is saved I recommend adding the line 

`delete $scope.registration.confirmPassword;`

on line 114.

**Comment by beeman** [comment]
Thanks for this message, fixed in ebec6228d26fc3aae723a2f28dd99ea9f7f247aa , in branch develop now :)
