### ISSUE TITLE
Adding support for Stormpath

### ISSUE THREAD

**Issue by adriatic** [beeman/loopback-angular-admin#74]
While it is pretty obvious (at least from my viewpoint) that LoopBack is the best overall NodeJS framework, it is quite thin on the "client side". This ```loopback-angular-admin``` is the best proof of my assessment -- since I found this project getting ready to create an extension of LoopBack Yeoman generator ```slc loopback``` that would do as good job creating client side skeleton app as it does on the server side. 

Now, always looking to improve what is available, I realized that Loopback would be a lot more useful when utilizing [Stormpath Authentication & User Management API](https://stormpath.com/) instead of it's own much less ambitious equivalent code. Since I am already working with Stormpath's team on "Stormpath - LoopBack" interface, it would be great to include that in ```loopback-angular-admin``` project.

At the moment, I am trying to verify the whole concept by "hand-patching" the skeleton created by '``loopback-angular-admin```

**Comment by Acaspita** [comment]
Great! Do it and let us know how it goes..., what are the limits of users when using free suscription Stormpath?

**Comment by adriatic** [comment]
There are no limits other than than those defined by Stormpath and LoopBack (both being open source project, free to everyone).

The original concept (StrongStorm) has since expanded in scope and you can watch its advancements at http://blog/congral.com - the article http://blog.congral.com/strongstorm-navigation-guide/ in particular.

**Comment by Acaspita** [comment]
Oh.., this is great then!...
Hey, how could we solve this that I exposed, with Stormpath? It's about limiting access to sections of the views depending on authorization roles. What do you think?
https://github.com/beeman/loopback-angular-admin/issues/77

**Comment by adriatic** [comment]
I would think that StrongStorm project is best approach for your needs - but that has barely started without any firm commitment for delivery. Check http://blog.congral.com/2015/05/17/vancouver-project/ to get some hints what we plan to do.

**Comment by macbroadcast** [comment]
I think there is some clarification needed, stormpath isnt opensource, just the SDK for accessing their APIs is opensource, thats why its called AaaS. I was following the development of strongloop for quite a while and i was fascinated like most of us , but at the end its just a hype from a company with a lot of venture capital in the background and the framework is way to complex and creates a lot of overhead. :smiley:

**Comment by adriatic** [comment]
**I stand corrected**, sorry for the confusion created by my careless observation. Nevertheless, having Stormpath SDK and LoopBack as open source code, allows any application developer that has a contract to develop something "state of the art", to prototype the application for free and see all the code in order to better understand the interface.

**Comment by beeman** [comment]
As the Stormpath backend is not open source I will not consider using it in this project.
