### ISSUE TITLE
Problem in Deploying on local machine 

### ISSUE THREAD

**Issue by rizvanhaider** [beeman/loopback-angular-admin#76]
I am trying to run loopback-angular -admin on my laptop but when I start the project with command [slc run] then on browser the login page appears and it continuously blinks and console generates infinite number of errors in controllers and etc... below is a screen shot attached

![screenshot 5](https://cloud.githubusercontent.com/assets/9403438/7724200/dcb9b57a-ff08-11e4-9955-8f5124f89cf9.png)

**Comment by sakthideveloper** [comment]
Hi rizvanhaider,
 Check and make sure this changes from pull request https://github.com/beeman/loopback-angular-admin/pulls to fix your live reload issues.

**Comment by beeman** [comment]
Please reopen if it's still the same with the latest master :)
