### ISSUE TITLE
Best way/practice to limit view access to a module for a particular User Role?

### ISSUE THREAD

**Issue by Acaspita** [beeman/loopback-angular-admin#77]
Hi,

What should be the best way to limit view access to a module for a particular User Role?

Should the folder client/app/modules/my-module/ be restricted when loading?
Should I remove in some way line 'con.module.my-module', from client/app/js/app.js folder?
and also remove js files loading at client/app/index.html ?
Or should I just not load files at client/app/modules/my-module/config/ folder? So that the item in the side bar and the routes not be configured?

What do you think should be the best strategy to take and what would be the best way to implement it?

Regards!

**Comment by beeman** [comment]
Hi @Acaspita I have only briefly looked at securing the project and thought about using something like angular-permissions, though that will bring security on a 'logical' level.

If you want to protect your users from accessing the content of certain modules I guess it's best to just remove them.

Please create a new issue if you have a specific example if something is not working as expected. Best would be to have an example of the code that's not working :)

**Comment by Acaspita** [comment]
Ok
