### ISSUE TITLE
Problem running npm start

### ISSUE THREAD

**Issue by kentyap** [beeman/loopback-angular-admin#78]
I encounter the following problem after running npm start fresh after installation

It keep flashing 
Get http://0.0.0.0:3000/api/AuthProviders/count net::ERR_ADDRESS_INVALID

![image](https://cloud.githubusercontent.com/assets/10970256/7896161/c1095e70-06e2-11e5-8a23-52e51486d6d3.png)

**Comment by beeman** [comment]
Please try to run `grunt build` after `npm install`, this should fix the issue for now. This is a known bug.

**Comment by kentyap** [comment]
I am sorry, I erase the directory to redo again and execute grunt build after npm install.  but  still with the same problem 
![image](https://cloud.githubusercontent.com/assets/10970256/7979996/d0e44bec-0a58-11e5-909e-b2a90bc8d6a8.png)

**Comment by beeman** [comment]
Can you check if the API is running at http://0.0.0.0/api ?

**Comment by kentyap** [comment]
[image: Inline image 1]

**Comment by beeman** [comment]
Hey @kentyap the image is not visible on github.com...

**Comment by kentyap** [comment]
![image](https://cloud.githubusercontent.com/assets/10970256/7980369/c2eee030-0a5b-11e5-990c-aa8611d5eaab.png)

Please see attached

**Comment by beeman** [comment]
Looks like the API is running. http://localhost:3000/api/notes should for instance give some results.

Can you try to to put  `API_URL=http://localhost:3000/api` in front of the command you are using to start the server?

**Comment by kentyap** [comment]
![image](https://cloud.githubusercontent.com/assets/10970256/7980844/bae15d92-0a5f-11e5-88d2-1fc9a4aed4a8.png)

Thanks please see attached, fail to login using admin@/admin.com and  user@user.com so try to register but has an error on the login page.

**Comment by beeman** [comment]
@kentyap that is probably because the initial dataset is not loaded if you don't specify it. Set `INITDB=true` to get that running, as specified in the README :)

Looking at the error message in this screen it looks like you haven't set a password.

**Comment by kentyap** [comment]
Thanks , manage to login now.

**Comment by beeman** [comment]
:+1:
