### ISSUE TITLE
Social connect

### ISSUE THREAD

**Issue by dthib** [beeman/loopback-angular-admin#80]
Hi,

I am trying to use the social connect feature with facebook but I am a bit stuck:
I have modified providers.json to leave only local facebook and I have fill the clientID & clientSecret fields. When I click on connect, I can see the redirection to facebook because at the beginning I got an invalid url error. After changing the website url in my facebook account to "http://localhost:3000/auth/facebook/callback", everything seems to work well except that I am still getting a 401 error so that I am stuck to the login page.
In the backend log, I can see that I am correctly logged in.
I guess it's a redirection issue. I don't know how to debug that because I don't know exactly the login process. Any help appreciated.

Thanks!

**Comment by dthib** [comment]
I keep on working on the subject and I have some more information:
- get the 401 because of the call : User.getCurrent() in main.ctrl.js.
- Inside this call this is is due to undefined LoopBackAuth.currentUserId.
- It seems that LoopBackAuth.setUser is not called in the case of social logging

if I replace the User.getCurrent() call by:
    AppAuth.ensureHasCurrentUser(function(user)
    {
      $scope.currentUser = user;
    });
in main.ctrl.js, it's working.

can you confirm that my understanding is correct? Do I have to commit or am I missing something?

Thank you,
Best regards

**Comment by beeman** [comment]
Hey @dthib , if you can send a pull request I will absolutely consider merging it!

Please on functionality/fix per branch :)

**Comment by dthib** [comment]
Hi beeman,
To be honest this is my first open source commit :). So I hope I did it the right way with the pull request.
Best,
Thibaut

**Comment by beeman** [comment]
Thanks! Just took the time to test and merge it!
