### ISSUE TITLE
This isn't an issue, more of a question, createRole.principals.create

### ISSUE THREAD

**Issue by LetsDoIt-** [beeman/loopback-angular-admin#81]
Can you please explain what is RoleMapping.USER ? I tried to go through the api docs but it's hard to understand,
createdRole.principals.create({
                  principalType: RoleMapping.USER,
                  principalId: createdUser.id
                },

Is RoleMapping.USER the User Model object ? or is the role user ? or is it just a enum ?

Does it have to change according to the role ? like RoleMapping.ADMIN and RoleMapping.STUDENT (New role i have created) ?

**Comment by beeman** [comment]
Hi @LetsDoIt- I am not sure to answer this question at the moment as my knowledge of the LoopBack ACL is still under par.

For general questions about LoopBack I recommend you to go to one of these gitter rooms and ask there:

https://gitter.im/strongloop/loopback
https://gitter.im/loopbackers/loopbackers.github.io
