### ISSUE TITLE
Integration to my own Loopback App ?

### ISSUE THREAD

**Issue by samuelbriole** [beeman/loopback-angular-admin#85]
I don't understand how I can integrate this admin client to my own loopback App, how can I generate the right html/js files ?

**Comment by Acaspita** [comment]
Emmmm..., I really don't get what you want to know..., besides pointing out that you don't understand how everything works around loopback and the client app...

Samuel, I think you should first study better the functioning of the framework, and later, if you get to know how the angular application works, then you'll realize how to do whatever you want to do, right?

....
