### ISSUE TITLE
Heroku Deployment Issue

### ISSUE THREAD

**Issue by thekennysong** [beeman/loopback-angular-admin#86]
Hello, 

First, I LOVE THIS! You did a really good job. When I deployed the app, I noticed some of the styles are messed up. You can check it out here, https://form-fun.herokuapp.com/

Thanks!

Kenny

**Comment by beeman** [comment]
Hi @thekennysong , thanks a lot!

It should be fixed now, this was a duplicate of [this bug](https://github.com/beeman/loopback-angular-admin/issues/84#issuecomment-113570352)
