### ISSUE TITLE
Connecting Loopback w/DB

### ISSUE THREAD

**Issue by thekennysong** [beeman/loopback-angular-admin#88]
Hello, 

Noticed that after a bit, the stored data goes away. I am assuming the app uses local storage? Anyway, I am trying to make the platform so it permanently saves data? Any suggestions? 

Kenny

**Comment by beeman** [comment]
Hi @thekennysong, this project uses the [loopback memory connector](http://docs.strongloop.com/display/public/LB/Memory+connector) by default. It is probably best to use MongoDB with this project, in the README you can find how to configure that.

**Comment by thekennysong** [comment]
I get this now when I try to run locally (INITDB=true MONGODB_URL="mongodb:/ocalhost:27017/loopback-angular-admin" sudo npm start), 

![screen shot 2015-06-24 at 9 39 29 am](https://cloud.githubusercontent.com/assets/5256555/8332712/f519b89c-1a54-11e5-8ed9-500167e35723.png)

**Comment by thekennysong** [comment]
Okay. So I reverted my steps and when I did the one line command so I can work on it locally, I got this
![screen shot 2015-06-25 at 9 19 24 am](https://cloud.githubusercontent.com/assets/5256555/8356510/6e657d1e-1b1b-11e5-8aa0-6f45e65317d5.png)

**Comment by beeman** [comment]
Please reopen if it's still the same with the latest master :)

**Comment by thekennysong** [comment]
![screen shot 2015-07-01 at 11 17 45 am](https://cloud.githubusercontent.com/assets/5256555/8459440/dcabc3ac-1fe2-11e5-90dd-2dfa6bb6f661.png)

I did sudo chown -R $(whoami) ~/.npm/_locks and sudo npm install npm -g to try and solve the issue. No luck :(

**Comment by beeman** [comment]
Can you try running the 'one-liner install' in a separate directory to see if that still fails?

**Comment by thekennysong** [comment]
I have been using sudo for npm and --force for grunt because otherwise I won't get as far. I have been doing the one-liner install as well. Should I send a video of what the terminal does. I believe this repo is fine but I just don't get why it won't locally on my machine.

**Comment by beeman** [comment]
I guess you should always try and avoid using `--force` parameters. It will be best to try and clean your current node installation and retry. On OS X I have never used sudo with npm, it's all installed in user land. I have installed node using homebrew.

For issues regarding to the working of node in general on your mac please refer to other places like this one: http://nodeslackers.io/ as I don't have the time to solve the issues on your machine, sorry.

**Comment by thekennysong** [comment]
No worries, appreciate the time! Will let you know what does the trick. 

Cheers from Chicago!

Kenny
