### ISSUE TITLE
loopback-connector-mongodb needs to be updated for ctx.isNewInstance to work

### ISSUE THREAD

**Issue by asgeirbirkis** [beeman/loopback-angular-admin#92]
Strongloop is advocating the use of operation hooks instead of deprecated model hooks. One nice thing that comes with that functionality is the `ctx.isNewInstance`, cf. http://docs.strongloop.com/display/public/LB/Operation+hooks#Operationhooks-Checkingforsupportofctx.isNewInstance

However, this functionality only got introduced in v1.9.0 of loopback-connector-mongodb, but the current package.json is fixed at v1.7.0.

Simply updating package.json to use v1.11.3 of loopback-connector-mongodb causes another error, which can be fixed by updating loopback-datasource-juggler to the latest version, v2.33.1.

This again requires loopback to be updated, I was successful using the latest version, v2.19.0.

Finally, by adding `"legacyExplorer": false` in server/config.json, deprecation warnings otherwise printed go away.

Making these changes seem to work fine when doing a new install, I'm happy to submit a pull request for this if you'd like.

**Comment by beeman** [comment]
Hi @asgeirbirkis, thanks for you issue. I agree with making the above changes and I'm happy to accept it as a PR :)
