### ISSUE TITLE
Upgrade to AdminLTE v2.2

### ISSUE THREAD

**Issue by matoho** [beeman/loopback-angular-admin#95]
AdminLTE offers a new version and it would be neat if it was updated within loopback-angular-admin.

Cheers

**Comment by beeman** [comment]
Hi @matoho, thanks for you issue.

AdminLTE is awesome and especially the 2.2 branch. There are a couple of reasons why I'll probably switch to using another theme in the future, the main reason is that AdminLTE is not built for AngularJS. That means there will be a lot non-angular code in the system, and I don't like that idea. 

Next to that the theme has a lot of plugins that I don't see fit in the project in it's current state, so it's quite a heavy solution (I'd almost say bloated).

I hope you understand! :)
